# Transcribe audio 

Transcribes all the videos in given folder, then attributes and stitches together transcripts based on the saved recording ids.
If recording IDs get missed, we don't stitch them into the final version, so maybe should write a check for that.

In [1]:
! pip install --upgrade deepgram-sdk
! pip install boto3
! pip install python-dotenv

Requirement already satisfied: deepgram-sdk in /opt/anaconda3/lib/python3.12/site-packages (4.1.0)
Collecting deepgram-sdk
  Using cached deepgram_sdk-4.5.0-py3-none-any.whl.metadata (26 kB)
Requirement already satisfied: httpx>=0.25.2 in /opt/anaconda3/lib/python3.12/site-packages (from deepgram-sdk) (0.28.1)
Requirement already satisfied: websockets>=12.0 in /opt/anaconda3/lib/python3.12/site-packages (from deepgram-sdk) (15.0.1)
Requirement already satisfied: dataclasses-json>=0.6.3 in /opt/anaconda3/lib/python3.12/site-packages (from deepgram-sdk) (0.6.7)
Requirement already satisfied: typing_extensions>=4.9.0 in /opt/anaconda3/lib/python3.12/site-packages (from deepgram-sdk) (4.11.0)
Requirement already satisfied: aiohttp>=3.9.1 in /opt/anaconda3/lib/python3.12/site-packages (from deepgram-sdk) (3.9.5)
Requirement already satisfied: aiofiles>=23.2.1 in /opt/anaconda3/lib/python3.12/site-packages (from deepgram-sdk) (24.1.0)
Requirement already satisfied: aenum>=3.1.0 in /opt/anaconda3/lib/python3.12/site-packages (from deepgram-sdk) (3.1.16)
Requirement already satisfied: deprecation>=2.1.0 in /opt/anaconda3/lib/python3.12/site-packages (from deepgram-sdk) (2.1.0)
Requirement already satisfied: aiosignal>=1.1.2 in /opt/anaconda3/lib/python3.12/site-packages (from aiohttp>=3.9.1->deepgram-sdk) (1.2.0)
Requirement already satisfied: attrs>=17.3.0 in /opt/anaconda3/lib/python3.12/site-packages (from aiohttp>=3.9.1->deepgram-sdk) (23.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /opt/anaconda3/lib/python3.12/site-packages (from aiohttp>=3.9.1->deepgram-sdk) (1.4.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /opt/anaconda3/lib/python3.12/site-packages (from aiohttp>=3.9.1->deepgram-sdk) (6.0.4)
Requirement already satisfied: yarl<2.0,>=1.0 in /opt/anaconda3/lib/python3.12/site-packages (from aiohttp>=3.9.1->deepgram-sdk) (1.9.3)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in /opt/anaconda3/lib/python3.12/site-packages (from dataclasses-json>=0.6.3->deepgram-sdk) (3.26.1)
Requirement already satisfied: typing-inspect<1,>=0.4.0 in /opt/anaconda3/lib/python3.12/site-packages (from dataclasses-json>=0.6.3->deepgram-sdk) (0.9.0)
Requirement already satisfied: packaging in /opt/anaconda3/lib/python3.12/site-packages (from deprecation>=2.1.0->deepgram-sdk) (23.2)
Requirement already satisfied: anyio in /opt/anaconda3/lib/python3.12/site-packages (from httpx>=0.25.2->deepgram-sdk) (4.2.0)
Requirement already satisfied: certifi in /opt/anaconda3/lib/python3.12/site-packages (from httpx>=0.25.2->deepgram-sdk) (2024.8.30)
Requirement already satisfied: httpcore==1.* in /opt/anaconda3/lib/python3.12/site-packages (from httpx>=0.25.2->deepgram-sdk) (1.0.9)
Requirement already satisfied: idna in /opt/anaconda3/lib/python3.12/site-packages (from httpx>=0.25.2->deepgram-sdk) (3.7)
Requirement already satisfied: h11>=0.16 in /opt/anaconda3/lib/python3.12/site-packages (from httpcore==1.*->httpx>=0.25.2->deepgram-sdk) (0.16.0)
Requirement already satisfied: mypy-extensions>=0.3.0 in /opt/anaconda3/lib/python3.12/site-packages (from typing-inspect<1,>=0.4.0->dataclasses-json>=0.6.3->deepgram-sdk) (1.0.0)
Requirement already satisfied: sniffio>=1.1 in /opt/anaconda3/lib/python3.12/site-packages (from anyio->httpx>=0.25.2->deepgram-sdk) (1.3.0)
Using cached deepgram_sdk-4.5.0-py3-none-any.whl (156 kB)
Installing collected packages: deepgram-sdk
  Attempting uninstall: deepgram-sdk
    Found existing installation: deepgram-sdk 4.1.0
    Uninstalling deepgram-sdk-4.1.0:
      Successfully uninstalled deepgram-sdk-4.1.0
Successfully installed deepgram-sdk-4.5.0
Collecting boto3
  Downloading boto3-1.39.4-py3-none-any.whl.metadata (6.6 kB)
Collecting botocore<1.40.0,>=1.39.4 (from boto3)
  Downloading botocore-1.39.4-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /opt/anaconda3/lib/python3.12/site-packages (from boto3) (1.0.1)
Collecting s3transfer<0.14.0,>=0.13.0 (from boto3)
  Downloading s3transfer-0.13.0-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /opt/anaconda3/lib/python3.12/site-packages (from botocore<1.40.0,>=1.39.4->boto3) (2.9.0.post0)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in /opt/anaconda3/lib/python3.12/site-packages (from botocore<1.40.0,>=1.39.4->boto3) (2.2.2)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.12/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.40.0,>=1.39.4->boto3) (1.16.0)
Downloading boto3-1.39.4-py3-none-any.whl (139 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.9/139.9 kB 5.6 MB/s eta 0:00:00
Downloading botocore-1.39.4-py3-none-any.whl (13.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 18.0 MB/s eta 0:00:0000:0100:01
Downloading s3transfer-0.13.0-py3-none-any.whl (85 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.2/85.2 kB 9.1 MB/s eta 0:00:00
Installing collected packages: botocore, s3transfer, boto3
  Attempting uninstall: botocore
    Found existing installation: botocore 1.34.69
    Uninstalling botocore-1.34.69:
      Successfully uninstalled botocore-1.34.69
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
aiobotocore 2.12.3 requires botocore<1.34.70,>=1.34.41, but you have botocore 1.39.4 which is incompatible.
Successfully installed boto3-1.39.4 botocore-1.39.4 s3transfer-0.13.0
Requirement already satisfied: python-dotenv in /opt/anaconda3/lib/python3.12/site-packages (0.21.0)

In [9]:
import os
import glob
import re
import pandas as pd
import json
from dotenv import load_dotenv
from deepgram import ( DeepgramClient , FileSource, PrerecordedOptions )
import shutil

load_dotenv()

recordings_folder = 'recordings'

API_KEY = os.getenv("DG_API_KEY")
deepgram = DeepgramClient(API_KEY)

In [4]:
# transcribe files and create utterances and words csvs for each audio file
audio_files = glob.glob(f'recordings/2025*_pilot*/*audio*.webm', recursive=True)

for audio_file in audio_files:
    utterances_filepath = audio_file.replace(".webm", "-utterances.csv")
    words_filepath = audio_file.replace(".webm", "-words.csv")
    if not os.path.exists(utterances_filepath):
        print("===================================================================================")
        print("transcribing", audio_file)
        
        # get time offset by filepath timestamp
        group_start = int(audio_file.split("/")[-1].split('-')[0])
        filepath_start = int(audio_file.split('-')[-1].split('.')[0])
        filepath_offset = (filepath_start - group_start)/1000

        # get time offset by audio file internal start time
        output = ! ffprobe $audio_file
        start_time_match = re.search(' start: (\d+\.\d+)', '\n'.join(output))
        timestamp_offset = float(start_time_match.group(1)) if start_time_match else None

        if abs(timestamp_offset - filepath_offset) > 1:
            print(f"Warning: timestamp_offset {timestamp_offset} and filepath_offset {filepath_offset} are more than 1 second apart")
    
        with open(audio_file, "rb") as file:
            buffer_data = file.read()

        payload: FileSource = {
            "buffer": buffer_data,
        }

        #STEP 2: Configure Deepgram options for audio analysis
        options = PrerecordedOptions(
            model="nova-2",
            utterances=True,
        )

        # STEP 3: Call the transcribe_file method with the text payload and options
        response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)


        if len(response.to_dict()['results']['utterances']) == 0:
            print("no words in", audio_file)
            pd.DataFrame().to_csv(utterances_filepath, index=False) # create empty file
            continue


        transcription_df = pd.DataFrame(response.to_dict()['results']['utterances'])

        # export utterances csv
        utterances = transcription_df[["start", "end", "confidence", "transcript"]]
        utterances = utterances.rename(columns={"start": "raw_start", "end": "raw_end"})

        utterances["filepath_start"] = utterances["raw_start"] + filepath_offset
        utterances["filepath_end"] = utterances["raw_end"] + filepath_offset

        utterances['timestamp_start'] = utterances['raw_start'] + timestamp_offset
        utterances['timestamp_end'] = utterances['raw_end'] + timestamp_offset
        utterances.to_csv(utterances_filepath, index=False)

        # export words csv
        words_list = []
        for j, word_row in transcription_df.iterrows():
            words_list += word_row['words']

        words = pd.DataFrame(words_list)
        words = words.rename(columns={"start": "raw_start", "end": "raw_end"})

        words['filepath_start'] = words['raw_start'] + filepath_offset
        words['filepath_end'] = words['raw_end'] + filepath_offset

        words['timestamp_start'] = words['raw_start'] + timestamp_offset
        words['timestamp_end'] = words['raw_end'] + timestamp_offset
        words.to_csv(words_filepath, index=False)

===================================================================================
transcribing recordings/20250708_1813_pilotTD1HQA/1752000906031-875ed072-9a27-42db-9239-856bbd5311b9-cam-audio-1752000907087.webm

<>:18: SyntaxWarning: invalid escape sequence '\d'
<>:18: SyntaxWarning: invalid escape sequence '\d'
/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:18: SyntaxWarning: invalid escape sequence '\d'
  start_time_match = re.search(' start: (\d+\.\d+)', '\n'.join(output))
/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250708_1813_pilotTD1HQA/1751999778086-7dc250b2-b0dd-4d0d-a829-f67b47cc9233-cam-audio-1751999779141.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250708_1813_pilotTD1HQA/1752000325421-1b6675b2-0ac4-48c6-bac5-1fbc37a98fe1-cam-audio-1752000326792.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250708_1813_pilotTD1HQA/1752000726630-6e06ab3c-48a4-445a-9fc7-2678546e5a48-cam-audio-1752000727730.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250708_1813_pilotTD1HQA/1752000906031-25f582e5-959e-4049-a34a-92af3aabddbb-cam-audio-1752000907078.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250708_1813_pilotTD1HQA/1751999778086-b5e1dbec-7359-4e25-a130-7f863af5def4-cam-audio-1751999779137.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250708_1813_pilotTD1HQA/1752000726630-07530a99-82c9-4634-b759-7e45ddca2dd1-cam-audio-1752000727721.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250708_1813_pilotTD1HQA/1752000325421-54e75f25-4f5f-4668-9670-72e755fd38d2-cam-audio-1752000326800.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250618_1821_pilotRFMEFG/1750272345444-f904aa78-6e66-418c-805b-4046dcfe6309-cam-audio-1750272346566.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250618_1821_pilotRFMEFG/1750272345444-130172c6-c4fd-4278-8687-a5bf945c24fd-cam-audio-1750272346562.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250618_1821_pilotRFMEFG/1750271878825-41301c28-9076-47db-9840-f40d5ce05882-cam-audio-1750271879919.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250618_1821_pilotRFMEFG/1750272757788-ac480359-3107-4b59-8991-baff24cd9915-cam-audio-1750272758902.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250618_1821_pilotRFMEFG/1750272613096-8d43e913-48d0-438d-8213-10ee30256d65-cam-audio-1750272614921.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250618_1821_pilotRFMEFG/1750272757788-e1b42151-4067-4845-9f54-a5a93b979eee-cam-audio-1750272758900.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250618_1821_pilotRFMEFG/1750271878825-eeeb43b1-c426-4885-bcd5-71a0f2479fe7-cam-audio-1750271879924.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250618_1821_pilotRFMEFG/1750272613096-9cfc075a-198c-4351-a69f-17349e582f5e-cam-audio-1750272614136.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250429_1536_pilot3K2CNC/1745942313846-f7527764-5e75-458e-abe3-b8604fa03752-cam-audio-1745942323454.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250429_1536_pilot3K2CNC/1745942313846-1b667f8d-129c-471b-ace0-dfca2eda353c-cam-audio-1745942315119.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250317_1538_pilotA1PQHB2/1742229268411-cd1e49ec-08ac-4db3-aab3-1286ecf90524-cam-audio-1742229269182.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250317_1538_pilotA1PQHB2/1742229390469-138c0f92-93f9-432f-840e-a2450589f697-cam-audio-1742229539979.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250317_1538_pilotA1PQHB2/1742229390469-8bb666e1-0489-4696-9dcc-141bf9b039f8-cam-audio-1742229408505.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250317_1538_pilotA1PQHB2/1742229268411-5dee158d-d1d3-4160-8f15-b477473f734d-cam-audio-1742229268796.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250317_1538_pilotA1PQHB2/1742229951448-5e64b63d-ef18-4e41-916e-2e1aab0e4607-cam-audio-1742229951795.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250317_1538_pilotA1PQHB2/1742228796215-04f1e1e7-8c0d-4aa1-885d-9592ac0f0c78-cam-audio-1742228799737.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250317_1538_pilotA1PQHB2/1742229390469-8bb666e1-0489-4696-9dcc-141bf9b039f8-cam-audio-1742229390807.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

no words in recordings/20250317_1538_pilotA1PQHB2/1742229390469-8bb666e1-0489-4696-9dcc-141bf9b039f8-cam-audio-1742229390807.webm
===================================================================================
transcribing recordings/20250317_1538_pilotA1PQHB2/1742229390469-caf9a2e7-0ca4-4a99-b722-c170f5d74c5d-cam-audio-1742229390811.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250317_1538_pilotA1PQHB2/1742228796215-01419305-5cfb-44b9-bdea-af285cd7cc3e-cam-audio-1742228797082.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250317_1538_pilotA1PQHB2/1742229951448-5e07f241-8dd3-4664-951e-2cfabdd9b394-cam-audio-1742229951791.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250317_1538_pilotA1PQHB2/1742228796215-dc3092e8-265f-4ab0-b87d-4c074345ab40-cam-audio-1742228960677.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250317_1538_pilotACQP57H/1742228986959-166d2394-2bba-4863-b6e0-ae5bd16d59f2-cam-audio-1742228987803.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250317_1538_pilotACQP57H/1742228668426-4b76dc6c-663d-4244-a628-08d5eb4f82c3-cam-audio-1742228669276.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250317_1538_pilotACQP57H/1742227623695-7856c008-5576-4db3-a877-a5d8ae025eca-cam-audio-1742227624568.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250317_1538_pilotACQP57H/1742228232154-50ec29d7-2330-4743-b2e4-33c74b7d25c6-cam-audio-1742228232963.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250317_1538_pilotACQP57H/1742228986959-1bb866a2-bd06-4f7b-a881-6f8b2a553a6b-cam-audio-1742228987800.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250317_1538_pilotACQP57H/1742227623695-1dfee60d-0400-4116-b4a5-c2e3ea0e5aaf-cam-audio-1742227624566.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250317_1538_pilotACQP57H/1742228232154-34164720-7096-4188-a463-33a3838dcd21-cam-audio-1742228232966.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250317_1538_pilotACQP57H/1742228668426-8b815afe-703f-403c-851a-dc594e59b600-cam-audio-1742228669273.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250618_1821_pilotXX6T5Y/1750273282311-f104966e-2d93-48e6-bbe6-081f69eb75e2-cam-audio-1750273283555.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250618_1821_pilotXX6T5Y/1750272704433-cd0f8b79-104c-43fd-ad53-93f37522f480-cam-audio-1750272705501.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250618_1821_pilotXX6T5Y/1750272704433-e13284bf-7a80-4401-b1e8-8da43834cf3c-cam-audio-1750272876577.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250618_1821_pilotXX6T5Y/1750272289727-9f55bf28-ae52-490f-95ab-c3509cbca2b7-cam-audio-1750272290980.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250618_1821_pilotXX6T5Y/1750272289727-7b4f7945-a841-4529-9336-87a6c59e762d-cam-audio-1750272380792.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250618_1821_pilotXX6T5Y/1750273282311-aa24fdb3-3cab-424d-a63a-72fe71879a79-cam-audio-1750273340455.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250618_1821_pilotXX6T5Y/1750272289727-f763cc88-53ca-4729-88b1-9f0ee0be07cd-cam-audio-1750272454316.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250618_1821_pilotXX6T5Y/1750272289727-62acad4b-5ecc-4bdc-ae87-f731b1f23308-cam-audio-1750272506243.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250618_1821_pilotXX6T5Y/1750272704433-f76b4b61-af52-43f8-8bbf-145df6e794ae-cam-audio-1750272822471.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250618_1821_pilotXX6T5Y/1750273282311-6788d9db-6200-43ad-8503-e42f76c7ca5a-cam-audio-1750273283559.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250618_1821_pilotXX6T5Y/1750272289727-5ef54e93-e208-4830-a72f-67653cf0b798-cam-audio-1750272290985.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250618_1821_pilotXX6T5Y/1750273095318-b9296914-e74f-4e60-8a9e-fe636d8ffc44-cam-audio-1750273096390.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250618_1821_pilotXX6T5Y/1750272704433-59057de7-f752-42c8-b936-d639d0eece32-cam-audio-1750272705505.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250618_1821_pilotXX6T5Y/1750273095318-84661893-1b5e-46f8-8796-7af29b6ea9c8-cam-audio-1750273096383.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250708_1813_pilotQ6ZARX/1752000034101-8f0932f3-4629-4379-a28f-9851df8c767f-cam-audio-1752000038326.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250708_1813_pilotQ6ZARX/1751999802371-476601be-c23d-4178-8aaf-cb0874f1fa01-cam-audio-1751999803406.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250708_1813_pilotQ6ZARX/1752000227432-ffa393bc-9ece-4698-b1b4-d2a72d17998a-cam-audio-1752000228649.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250708_1813_pilotQ6ZARX/1752000227432-77f230d5-ed3b-41c0-af93-59f3708114b1-cam-audio-1752000228654.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250708_1813_pilotQ6ZARX/1752000373332-93d82598-f2ca-4089-8287-d219cf367b2c-cam-audio-1752000374453.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250708_1813_pilotQ6ZARX/1751999802371-843eab21-9744-4e0d-92fb-8862c93b5d1c-cam-audio-1751999803402.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250708_1813_pilotQ6ZARX/1752000034101-3e39edc2-54be-40d2-84c3-37eb73a56765-cam-audio-1752000035345.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250708_1813_pilotQ6ZARX/1752000373332-d1a8b66b-8ca8-4ed7-8457-3debc57f7793-cam-audio-1752000374450.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250429_1536_pilot2K1VFC/1745943233824-b8d9c80f-fea2-4344-b40b-8f732e9ba636-cam-audio-1745943234984.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250429_1536_pilot2K1VFC/1745943233824-e5c47041-f7f8-49fe-b610-301b7c323a32-cam-audio-1745943234980.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250708_1813_pilotZN46AE/1751999673688-e5041683-53c6-4c81-b897-6d2b0dc98efe-cam-audio-1751999677928.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250708_1813_pilotZN46AE/1752000233012-08f4a11c-2d41-4bf3-8670-64742fcfae6e-cam-audio-1752000234252.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250708_1813_pilotZN46AE/1752000412233-289bd337-9a19-437c-90a4-8f97cfb2cd71-cam-audio-1752000413490.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250708_1813_pilotZN46AE/1751999960028-371715a6-6daa-4e4e-b840-1b1657917365-cam-audio-1751999961125.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250708_1813_pilotZN46AE/1752000233012-00e49343-9f07-4a72-ac12-02ee3c2d752c-cam-audio-1752000234246.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250708_1813_pilotZN46AE/1752000412233-21e0330f-56d6-4f61-a3f9-01e0b26f3fa6-cam-audio-1752000415052.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250708_1813_pilotZN46AE/1751999960028-d7405b91-0fb7-4f29-b138-0652dd8729f1-cam-audio-1751999961136.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250708_1813_pilotZN46AE/1751999673688-bef27b62-8926-4022-ad93-508391e656dc-cam-audio-1751999675155.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250317_1538_pilotAYTEHK8/1742229071542-099bd158-46c5-4696-9d56-f8e0bf7b7428-cam-audio-1742229071848.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250317_1538_pilotAYTEHK8/1742230231134-b3347a22-7003-43fc-8d47-6ab7d1da8959-cam-audio-1742230231740.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250317_1538_pilotAYTEHK8/1742230231134-ed733431-c68b-42b9-bcc1-92f8cd79d49d-cam-audio-1742230231402.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250317_1538_pilotAYTEHK8/1742229071542-8d9a7cc5-9a5d-4e4a-902c-72e19e2912ed-cam-audio-1742229071851.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250317_1538_pilotAYTEHK8/1742229939970-2177179a-de23-49bb-920c-c17159351ba3-cam-audio-1742229940825.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250317_1538_pilotAYTEHK8/1742229605884-f255d8db-d674-44e9-8dba-5151f2710e2c-cam-audio-1742229606825.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250317_1538_pilotAYTEHK8/1742229605884-5220f595-20ee-46f9-b695-c3c98242042c-cam-audio-1742229606823.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250317_1538_pilotAYTEHK8/1742229939970-88660084-f791-4de4-bca6-da338e49cd90-cam-audio-1742229940822.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250618_1821_pilot34BR1P/1750272310917-7af16c8b-0d7f-48bd-ab3c-09c354c47571-cam-audio-1750272311980.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250618_1821_pilot34BR1P/1750272633478-fa0ba124-1b9c-42bc-a491-f8a84d23315a-cam-audio-1750272634766.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

no words in recordings/20250618_1821_pilot34BR1P/1750272633478-fa0ba124-1b9c-42bc-a491-f8a84d23315a-cam-audio-1750272634766.webm
===================================================================================
transcribing recordings/20250618_1821_pilot34BR1P/1750272310917-6af1eeac-be95-4132-82ea-94e332d581de-cam-audio-1750272313591.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

no words in recordings/20250618_1821_pilot34BR1P/1750272310917-6af1eeac-be95-4132-82ea-94e332d581de-cam-audio-1750272313591.webm
===================================================================================
transcribing recordings/20250618_1821_pilot34BR1P/1750272867424-e45149aa-d6cc-4201-827f-7212ef878537-cam-audio-1750272868898.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250618_1821_pilot34BR1P/1750271953804-d83b1ff4-a831-4418-9a7c-1cc640ebe4ea-cam-audio-1750271954860.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

no words in recordings/20250618_1821_pilot34BR1P/1750271953804-d83b1ff4-a831-4418-9a7c-1cc640ebe4ea-cam-audio-1750271954860.webm
===================================================================================
transcribing recordings/20250618_1821_pilot34BR1P/1750272633478-3e71b4ba-9613-49e0-8404-49e197db9d66-cam-audio-1750272634759.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250618_1821_pilot34BR1P/1750272867424-996ab37a-9593-4e1c-8856-3a0e802d2098-cam-audio-1750272869765.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

no words in recordings/20250618_1821_pilot34BR1P/1750272867424-996ab37a-9593-4e1c-8856-3a0e802d2098-cam-audio-1750272869765.webm
===================================================================================
transcribing recordings/20250618_1821_pilot34BR1P/1750271953804-47150ec5-6c1c-4cc1-abca-2772bf3a223d-cam-audio-1750271955645.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250618_1821_pilot34BR1P/1750271953804-6e0b8055-3e36-4c10-b029-5baf6d0be6fb-cam-audio-1750271961404.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

no words in recordings/20250618_1821_pilot34BR1P/1750271953804-6e0b8055-3e36-4c10-b029-5baf6d0be6fb-cam-audio-1750271961404.webm
===================================================================================
transcribing recordings/20250317_1538_pilotA1C7NCA/1742230536975-4f05be37-3c00-4609-a521-fd075e8a6707-cam-audio-1742230537816.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250317_1538_pilotA1C7NCA/1742229990479-e09a236d-a782-44eb-aef8-9d904be36855-cam-audio-1742229991305.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250317_1538_pilotA1C7NCA/1742229433547-3a738461-9562-47aa-b6bc-571761685824-cam-audio-1742229434376.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250317_1538_pilotA1C7NCA/1742230339227-dee4f8fc-a3c9-4e59-8e57-870e9359961f-cam-audio-1742230340008.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250317_1538_pilotA1C7NCA/1742229990479-28f0dced-2b01-471e-a869-642de9d59e80-cam-audio-1742229991308.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250317_1538_pilotA1C7NCA/1742230536975-ab61e7e7-8205-45af-80f7-5f2cebd542f7-cam-audio-1742230537818.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250317_1538_pilotA1C7NCA/1742229433547-bad60ba4-fa7e-4385-8beb-64808cbb8baf-cam-audio-1742229434373.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250317_1538_pilotA1C7NCA/1742230339227-b0807c3c-4395-4d33-ac99-c44ddd9ad9ce-cam-audio-1742230340006.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250618_1821_pilotRTYG0G/1750271746560-f8ab95fe-def4-457b-93d1-f0dee1d7c792-cam-audio-1750271749814.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250618_1821_pilotRTYG0G/1750271746560-4a86c98b-cbd8-4850-86c6-0cb0b93e5751-cam-audio-1750271747750.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250618_1821_pilotRTYG0G/1750272468167-92317323-64b2-4001-a3de-914cab6a958c-cam-audio-1750272472072.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250618_1821_pilotRTYG0G/1750272468167-091516eb-ed86-44a3-a5aa-84628b84fac1-cam-audio-1750272469463.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250618_1821_pilotRTYG0G/1750272125726-aebe604f-2acb-4102-a94e-ecfff5e60b35-cam-audio-1750272129795.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250618_1821_pilotRTYG0G/1750272282846-0188682c-f7bb-47f6-ba3e-07e9af05f95f-cam-audio-1750272286182.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250618_1821_pilotRTYG0G/1750272125726-9cc0a0d1-96d8-46c3-9e89-3f7535fbf059-cam-audio-1750272126932.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250618_1821_pilotRTYG0G/1750272282846-1e6eadf4-1d80-41a8-9452-06cfb549ba9a-cam-audio-1750272284057.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250708_1813_pilotVQP5V1/1751999530166-3595ab53-3f91-4ffb-aa9b-5a38cd769dcf-cam-audio-1751999531217.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250708_1813_pilotVQP5V1/1752000489838-f6c009ae-70df-46ff-881d-ac3070bca152-cam-audio-1752000491081.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250708_1813_pilotVQP5V1/1751999971793-66aa98b6-769e-44f4-a76f-ba5bb082d40e-cam-audio-1751999973313.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250708_1813_pilotVQP5V1/1751999971793-aa1d11f6-238d-4c14-9988-b6bee794d116-cam-audio-1751999973309.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250708_1813_pilotVQP5V1/1752000489838-cd409115-1a42-4512-ab98-5d180622a1f5-cam-audio-1752000496042.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250708_1813_pilotVQP5V1/1752000279404-6aa07f5a-296e-446e-9773-5266dabbb6d0-cam-audio-1752000280672.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250708_1813_pilotVQP5V1/1751999530166-04ce6122-e305-41a4-9abd-211550a9e6d2-cam-audio-1751999531220.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250708_1813_pilotVQP5V1/1752000279404-b734b718-32c8-44d2-b68b-8771c902efba-cam-audio-1752000280667.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250708_1813_pilot2XT15E/1752000324437-5d1f0e7b-7837-4cd8-8a0f-7bdd493b11df-cam-audio-1752000325618.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250708_1813_pilot2XT15E/1752000924867-3ecbf83f-271b-4d3c-abc3-88857993be7a-cam-audio-1752000925947.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250708_1813_pilot2XT15E/1752000597133-f24e2e7b-679e-40cf-a861-c5cbb5a280b2-cam-audio-1752000598163.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250708_1813_pilot2XT15E/1752000597133-9245cd37-031a-4841-a5aa-7e8bfea20558-cam-audio-1752000598166.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250708_1813_pilot2XT15E/1752000786956-4ecd1639-baec-48b8-89cf-a793c6c590b4-cam-audio-1752000788033.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250708_1813_pilot2XT15E/1752000324437-f298def2-99d7-4f41-89fd-961d5878d824-cam-audio-1752000325630.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250708_1813_pilot2XT15E/1752000924867-ed3e131b-0af5-4215-9a1d-a39f850862e5-cam-audio-1752000925943.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250708_1813_pilot2XT15E/1752000786956-bd3d9f26-b98e-4b65-b78b-723805971f81-cam-audio-1752000788041.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250421_1915_pilotZ9333Z/1745263962848-1ba763ae-3e98-4f21-8065-79c68fafbeda-cam-audio-1745263963247.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250421_1915_pilotZ9333Z/1745263962848-2bdd5045-3004-40da-8d85-94e2ed798401-cam-audio-1745263964628.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250429_1536_pilotWPJCQQ/1745942550540-ee82a882-6f39-4dc6-9ff0-fa5d20f5a392-cam-audio-1745942551653.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250429_1536_pilotWPJCQQ/1745942550540-cbd0b3c1-6562-4ac4-8732-fe92db7cd347-cam-audio-1745942551659.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250708_1813_pilotFTM1KT/1752000165229-1f0da879-eece-42f6-b7cc-0bed4f30b87e-cam-audio-1752000166397.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250708_1813_pilotFTM1KT/1751999887066-197c5a1a-a81f-4b1f-8274-cb58befdef9d-cam-audio-1751999888290.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250708_1813_pilotFTM1KT/1752000165229-1858f1ed-1806-48ff-a96d-6fba909a522b-cam-audio-1752000166394.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250708_1813_pilotFTM1KT/1752000368241-e9540c27-74ee-4a6a-940c-a361ad91e6b0-cam-audio-1752000370266.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250708_1813_pilotFTM1KT/1751999637167-b46abb8a-28a4-4548-9e63-b9ee236c0b9f-cam-audio-1751999638418.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250708_1813_pilotFTM1KT/1751999887066-f782da8e-3d64-44d7-9bdc-44a8d5b4df4c-cam-audio-1751999888293.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250708_1813_pilotFTM1KT/1751999637167-8de778a0-b64f-4808-af89-3e4838db81d0-cam-audio-1751999638411.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250708_1813_pilotFTM1KT/1752000368241-8021f855-d358-4c36-8f3c-9a0f98e97175-cam-audio-1752000369441.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250429_1536_pilotS8E0YF/1745942648505-034ed120-9514-4c6f-ad01-9063d480fe2e-cam-audio-1745942649602.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250429_1536_pilotS8E0YF/1745942648505-45b27d35-46cf-4a38-b628-8f0f2bbd1169-cam-audio-1745942649607.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250429_1536_pilotJWMFFY/1745942030759-7ecd7a09-34c4-4fe0-bd1e-f7a4f8d42e35-cam-audio-1745942032383.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250429_1536_pilotJWMFFY/1745942030759-afed026a-9df4-40d4-91dd-019fe0808153-cam-audio-1745942032377.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250618_1821_pilotY15NND/1750272110426-12294207-b200-4ba1-b6e9-8cdfb4006fd9-cam-audio-1750272111512.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250618_1821_pilotY15NND/1750272616867-bcc64674-e1ff-4519-8650-0fdba9d948ab-cam-audio-1750272617985.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250618_1821_pilotY15NND/1750272983235-67ca18e2-6ce8-42c2-a605-0df7c6448728-cam-audio-1750272984345.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250618_1821_pilotY15NND/1750272616867-6bf3e22d-a3a7-44de-a277-3e6f5775ce50-cam-audio-1750272617976.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250618_1821_pilotY15NND/1750273191828-15e67368-5525-4d4a-9a88-6e438d8b3043-cam-audio-1750273192920.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250618_1821_pilotY15NND/1750273191828-a1110a59-7954-4259-9907-5be015e6ce15-cam-audio-1750273192925.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250618_1821_pilotY15NND/1750272110426-81a80875-5ea6-4e94-9122-c9ded2eef917-cam-audio-1750272111514.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250618_1821_pilotY15NND/1750272983235-9d320778-ecfa-4c4b-9dbe-58859c7da129-cam-audio-1750272984356.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250708_1813_pilot2BY1T9/1752000618158-f5911163-7e4d-4c49-bace-101297720f87-cam-audio-1752000619285.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250708_1813_pilot2BY1T9/1752000980607-cb9c8ec6-370e-466d-8026-7f612a8842c1-cam-audio-1752000981608.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250708_1813_pilot2BY1T9/1752000153821-7f8424cf-acbf-4ddb-a6fa-b10168e0b33f-cam-audio-1752000154909.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250708_1813_pilot2BY1T9/1752001203273-9835d752-67ce-472f-bace-dbd39650fd0d-cam-audio-1752001204662.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250708_1813_pilot2BY1T9/1752001203273-bc79f743-2aae-4323-9d99-661507726da3-cam-audio-1752001204651.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250708_1813_pilot2BY1T9/1752000153821-5fb8497a-8316-4fd3-8449-5f93606ba375-cam-audio-1752000154915.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250708_1813_pilot2BY1T9/1752000618158-97416ecd-2be5-4ff7-9025-87f47bf91a52-cam-audio-1752000619291.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250708_1813_pilot2BY1T9/1752000980607-c74d8394-4490-4aae-a025-ab066b17a2e0-cam-audio-1752000981614.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250618_1821_pilotTKB9T5/1750273516670-3d3cc53c-848e-4832-bcd5-5692797a7810-cam-audio-1750273517850.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250618_1821_pilotTKB9T5/1750273056133-295b644f-7f67-46b8-93c0-3b2550a609e1-cam-audio-1750273057179.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250618_1821_pilotTKB9T5/1750273056133-39d4c235-6245-4bdf-ae09-88fc86883069-cam-audio-1750273059539.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250618_1821_pilotTKB9T5/1750272501018-a8c80eb3-7d31-45cb-85ac-26b4fb56d24b-cam-audio-1750272504641.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250618_1821_pilotTKB9T5/1750273328019-9444d7c9-517a-4eb9-8240-9aa0f081d7bd-cam-audio-1750273329251.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250618_1821_pilotTKB9T5/1750272501018-d89deed0-2798-484c-9f28-5730017fd2b0-cam-audio-1750272502089.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250618_1821_pilotTKB9T5/1750273328019-9b171cc4-069c-4a5d-875f-e6d603624b6b-cam-audio-1750273329256.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250618_1821_pilotTKB9T5/1750273516670-a54028c2-1bf7-491b-a934-a058783fd477-cam-audio-1750273519189.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250708_1813_pilotAYS7KJ/1752000373776-a1808530-f34f-45a8-ba5b-8429efbf954b-cam-audio-1752000374985.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250708_1813_pilotAYS7KJ/1752000054659-605bf604-cd5c-42ba-bb95-7e6c56c7b592-cam-audio-1752000058358.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250708_1813_pilotAYS7KJ/1752000373776-2fae25bf-d431-4df2-a7c5-1f5cfa2f210f-cam-audio-1752000374989.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250708_1813_pilotAYS7KJ/1752000054659-3496cc13-24ca-4463-b7de-313744279842-cam-audio-1752000055863.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250708_1813_pilotAYS7KJ/1751999638506-bb7ecf05-454c-464a-96ae-2d19580deb79-cam-audio-1751999639768.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250708_1813_pilotAYS7KJ/1752000602122-408390cb-cadc-4cd2-850d-279f18deefbf-cam-audio-1752000603897.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250708_1813_pilotAYS7KJ/1752000602122-a178a715-b07a-400a-b89d-9ff879b4e14a-cam-audio-1752000603888.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250708_1813_pilotAYS7KJ/1751999638506-ad7eb959-1482-4645-ba3e-88a104e0d65f-cam-audio-1751999639776.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250317_1538_pilotAZ9FCA4/1742228116218-f6d28d2e-0540-44f9-9c76-3e62f2570d40-cam-audio-1742228116488.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250317_1538_pilotAZ9FCA4/1742228261392-f0a64ea9-bd65-4245-a4c5-3a97519de912-cam-audio-1742228261770.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250317_1538_pilotAZ9FCA4/1742228261392-ecee1031-9651-49c1-91c6-3b7585cf8101-cam-audio-1742228261773.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250317_1538_pilotAZ9FCA4/1742227989673-31b80f2a-a4a8-438e-95ca-3d263dfdf405-cam-audio-1742227989997.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250317_1538_pilotAZ9FCA4/1742228116218-4d467279-e679-4733-8ecf-04245a18d6b8-cam-audio-1742228120397.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250317_1538_pilotAZ9FCA4/1742227989673-939de4cc-c857-48ae-bc9e-8a953f488565-cam-audio-1742227989994.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250317_1538_pilotAZ9FCA4/1742227758747-0b21ca0c-51a0-48bc-a1f7-0725c4bcebba-cam-audio-1742227759244.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250317_1538_pilotAZ9FCA4/1742227758747-03fafa2b-32bb-4bdf-b945-f1860fbc66f6-cam-audio-1742227764841.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250317_1538_pilotAFW2686/1742228558976-75096281-10f2-4c98-b5c5-0e8c2a9ede71-cam-audio-1742228560111.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250317_1538_pilotAFW2686/1742228174589-3cce06a5-1ac3-44a0-b2d9-62acc8f3b9b3-cam-audio-1742228174878.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250317_1538_pilotAFW2686/1742228174589-cbed8857-9e7c-4171-8ac8-7761ee1cce77-cam-audio-1742228176321.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250317_1538_pilotAFW2686/1742228470083-e5183415-8639-4e8d-ace8-b60ed1d60af7-cam-audio-1742228470374.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250317_1538_pilotAFW2686/1742228558976-bf6feb7f-603e-4159-86e2-d395c298793e-cam-audio-1742228560113.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250317_1538_pilotAFW2686/1742228365802-9649acda-c5c9-450a-83d2-2a4c4d1dd315-cam-audio-1742228366128.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250317_1538_pilotAFW2686/1742228365802-584d8e06-978d-4dca-b893-a7a9e7683743-cam-audio-1742228366131.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250317_1538_pilotAFW2686/1742228470083-19d15e0c-0932-4651-a511-cc672c937465-cam-audio-1742228470370.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250429_1536_pilot9320NE/1745942274823-d9d58f88-ae65-42b7-a813-1a3d17d81658-cam-audio-1745942276085.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250429_1536_pilot9320NE/1745942274823-0ec71214-045a-49e5-ba3c-c282a41a6eeb-cam-audio-1745942276080.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250618_1821_pilotDM261K/1750272130270-a67ae6f4-99f1-49fe-a3d9-f2aed7729e49-cam-audio-1750272131348.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250618_1821_pilotDM261K/1750272381421-2c85b08a-3770-4538-b873-21b0bc56cb93-cam-audio-1750272382614.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250618_1821_pilotDM261K/1750272545903-4f494728-50af-427b-b2d5-d499d84bbd65-cam-audio-1750272548037.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250618_1821_pilotDM261K/1750271899979-d2eaad18-7692-402f-84de-1f6a7251d0fd-cam-audio-1750271901192.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250618_1821_pilotDM261K/1750272130270-aa5140e7-edbc-4be7-8be9-4dc73940009d-cam-audio-1750272131352.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250618_1821_pilotDM261K/1750271899979-dabfe240-49bc-47d8-b230-1e0c4c098598-cam-audio-1750271901199.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250618_1821_pilotDM261K/1750272545903-0aeb2e19-6a13-44ed-86b3-f16d2f061e37-cam-audio-1750272547121.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250618_1821_pilotDM261K/1750272381421-e2a68557-6b0d-408c-a4bd-2e4906c3ea58-cam-audio-1750272382619.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250618_1821_pilot63E4P3/1750272044099-342b0f9d-f0f2-4aa6-9d3b-8dee4bcf2791-cam-audio-1750272045178.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250618_1821_pilot63E4P3/1750271804487-e11096a6-d135-4cf6-b845-e625bdfe2585-cam-audio-1750271806458.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250618_1821_pilot63E4P3/1750271505366-6cbf9749-47a2-47c8-9915-d830ca12d19a-cam-audio-1750271506467.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250618_1821_pilot63E4P3/1750272044099-942ed1b4-1df5-41eb-8599-324e2f59dc52-cam-audio-1750272046182.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250618_1821_pilot63E4P3/1750272208534-6064838f-2449-493b-9e6d-c15141952d23-cam-audio-1750272209554.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250618_1821_pilot63E4P3/1750272208534-8b4da1aa-96a2-46eb-b867-cd4c51d5a82b-cam-audio-1750272210450.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250618_1821_pilot63E4P3/1750271804487-91b7d675-ec39-4371-a6b4-86a457e9d76d-cam-audio-1750271805645.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250618_1821_pilot63E4P3/1750271505366-125571c4-6f11-43e6-a7a2-7cbd5f7d7d82-cam-audio-1750271507288.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250317_1538_pilotA975XBN/1742226216060-b90f6024-5c23-4a25-9623-efab0f84fee8-cam-audio-1742226216407.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

no words in recordings/20250317_1538_pilotA975XBN/1742226216060-b90f6024-5c23-4a25-9623-efab0f84fee8-cam-audio-1742226216407.webm
===================================================================================
transcribing recordings/20250317_1538_pilotA975XBN/1742226216060-d1169a06-2a8e-459e-8a5c-12b32e7c8556-cam-audio-1742226235436.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

no words in recordings/20250317_1538_pilotA975XBN/1742226216060-d1169a06-2a8e-459e-8a5c-12b32e7c8556-cam-audio-1742226235436.webm
===================================================================================
transcribing recordings/20250317_1538_pilotA975XBN/1742226216060-e2791129-1f39-4cd7-b94f-594992d19a33-cam-audio-1742226216401.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

no words in recordings/20250317_1538_pilotA975XBN/1742226216060-e2791129-1f39-4cd7-b94f-594992d19a33-cam-audio-1742226216401.webm
===================================================================================
transcribing recordings/20250317_1538_pilotA3Q9H1Q/1742229776573-0f6ea65b-fad5-44af-88d1-4ee9066fe911-cam-audio-1742229777617.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250317_1538_pilotA3Q9H1Q/1742230731484-5d9d6736-09e9-42bd-81ca-1f348568c662-cam-audio-1742230732324.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250317_1538_pilotA3Q9H1Q/1742231179843-a0074852-8893-4b49-b988-a8086f8fa2ae-cam-audio-1742231185271.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

no words in recordings/20250317_1538_pilotA3Q9H1Q/1742231179843-a0074852-8893-4b49-b988-a8086f8fa2ae-cam-audio-1742231185271.webm
===================================================================================
transcribing recordings/20250317_1538_pilotA3Q9H1Q/1742229776573-ded881d1-fc64-42ce-b4f4-26ecddd08da1-cam-audio-1742229831091.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

no words in recordings/20250317_1538_pilotA3Q9H1Q/1742229776573-ded881d1-fc64-42ce-b4f4-26ecddd08da1-cam-audio-1742229831091.webm
===================================================================================
transcribing recordings/20250317_1538_pilotA3Q9H1Q/1742230285598-6fe6e946-2c4d-4f97-a15c-dcb7d45ffab1-cam-audio-1742230544058.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

no words in recordings/20250317_1538_pilotA3Q9H1Q/1742230285598-6fe6e946-2c4d-4f97-a15c-dcb7d45ffab1-cam-audio-1742230544058.webm
===================================================================================
transcribing recordings/20250317_1538_pilotA3Q9H1Q/1742230285598-72475cb8-739b-4b7b-9f87-bc138db1f8d6-cam-audio-1742230572757.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

no words in recordings/20250317_1538_pilotA3Q9H1Q/1742230285598-72475cb8-739b-4b7b-9f87-bc138db1f8d6-cam-audio-1742230572757.webm
===================================================================================
transcribing recordings/20250317_1538_pilotA3Q9H1Q/1742231179843-67d0541d-8941-4a23-bc0a-d0da3787aeda-cam-audio-1742231180707.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

===================================================================================
transcribing recordings/20250317_1538_pilotA3Q9H1Q/1742230731484-0a89d2e5-4b9d-4a76-8ef2-8f0f7354f44e-cam-audio-1742230732322.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

no words in recordings/20250317_1538_pilotA3Q9H1Q/1742230731484-0a89d2e5-4b9d-4a76-8ef2-8f0f7354f44e-cam-audio-1742230732322.webm
===================================================================================
transcribing recordings/20250317_1538_pilotA3Q9H1Q/1742230285598-53647a7b-2e40-46db-a46e-f67bb7c07125-cam-audio-1742230286399.webm

/var/folders/2l/3kmvzs0s1sggnw_9sl0ls8080000gn/T/ipykernel_98666/3309302444.py:38: UnsupportedWarning: prerecorded is unsupported as of 4.0.0. deepgram.listen.prerecorded is deprecated. Use deepgram.listen.rest instead.
  response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)

In [6]:
# Load the experiment data so we can assign positions and game ids to each utterance

# pd.options.display.max_rows = None
recordings = pd.read_csv('recordings/recordings_list.csv')
recordings.head().T

,0,1,2,3,4
path,recordings/20250618_1821_pilot34BR1P/175027195...,recordings/20250618_1821_pilot34BR1P/175027195...,recordings/20250618_1821_pilot34BR1P/175027195...,recordings/20250618_1821_pilot34BR1P/175027195...,recordings/20250618_1821_pilot34BR1P/175027195...
folder,20250618_1821_pilot34BR1P,20250618_1821_pilot34BR1P,20250618_1821_pilot34BR1P,20250618_1821_pilot34BR1P,20250618_1821_pilot34BR1P
filename,1750271953804-47150ec5-6c1c-4cc1-abca-2772bf3a...,1750271953804-47150ec5-6c1c-4cc1-abca-2772bf3a...,1750271953804-6e0b8055-3e36-4c10-b029-5baf6d0b...,1750271953804-6e0b8055-3e36-4c10-b029-5baf6d0b...,1750271953804-d83b1ff4-a831-4418-9a7c-1cc640eb...
date,20250618,20250618,20250618,20250618,20250618
time,1821,1821,1821,1821,1821
mtgStartTime,1750271953804,1750271953804,1750271953804,1750271953804,1750271953804
sessionId,47150ec5_6c1c_4cc1_abca_2772bf3a223d,47150ec5_6c1c_4cc1_abca_2772bf3a223d,6e0b8055_3e36_4c10_b029_5baf6d0be6fb,6e0b8055_3e36_4c10_b029_5baf6d0be6fb,d83b1ff4_a831_4418_9a7c_1cc640ebe4ea
group,pilot34BR1P,pilot34BR1P,pilot34BR1P,pilot34BR1P,pilot34BR1P
filetype,audio,video,audio,video,audio
gameId,01JY25CKAD4BKEXHF4Q934BR1P,01JY25CKAD4BKEXHF4Q934BR1P,01JY25CKAD4BKEXHF4Q934BR1P,01JY25CKAD4BKEXHF4Q934BR1P,01JY25CKAD4BKEXHF4Q934BR1P
position,0,0,1,1,1
sampleId,f23993e7-7dd8-4037-b202-ef490437583a,f23993e7-7dd8-4037-b202-ef490437583a,c5945742-38e0-4b32-99c4-9a18ae23c4e0,c5945742-38e0-4b32-99c4-9a18ae23c4e0,c5945742-38e0-4b32-99c4-9a18ae23c4e0

# Compile utterances csv for each group

In [22]:
# Define the destination folder for finalized files
READY_TO_CODE_DIR = "recordings/ready_to_code"

# Build overall utterances csv for each game
for game_index, group in recordings.groupby(["group", "mtgStartTime"]):
    conversation_utterances = pd.DataFrame()
    group_folder = f"{recordings_folder}/{group['folder'].iloc[0]}"
    for i, row in group.iterrows():
        if row['filetype'] != 'audio':
            continue

        try:
            utterances_df = pd.read_csv(f"{group_folder}/{row['filename']}".replace(".webm", "-utterances.csv"))
            utterances_df["conversation_id"] = row['mtgStartTime']
            utterances_df["position"] = row['position']

            conversation_utterances = pd.concat([conversation_utterances, utterances_df])
        except Exception as e:
            print(f"Error processing {row['filename']}: {e}")
            continue

    if conversation_utterances.shape[0] == 0:
        print(f"❌ no utterances found for folder {group_folder}")
        continue

    try:
        conversation_utterances.sort_values(by=['timestamp_start'], inplace=True)
        output_path = f"{group_folder}/{row['mtgStartTime']}_group-utterances.csv"
        conversation_utterances.to_csv(output_path, index=False)

        # Copy the finalized file
        date, time, group_id = group_folder.split("/")[-1].split("_")
        new_filename = f"{date}_{time}_group_{group_id}_{row['mtgStartTime']}_utterances.csv"
        destination_path = os.path.join(READY_TO_CODE_DIR, new_filename)
        shutil.copy(output_path, destination_path)
        print(f"👉 Copied to: {destination_path}")
    except:
        print("problem with group", group_id)

👉 Copied to: recordings/ready_to_code/20250708_1813_group_pilot2BY1T9_1752000153821_utterances.csv
👉 Copied to: recordings/ready_to_code/20250708_1813_group_pilot2BY1T9_1752000618158_utterances.csv
👉 Copied to: recordings/ready_to_code/20250708_1813_group_pilot2BY1T9_1752000980607_utterances.csv
👉 Copied to: recordings/ready_to_code/20250708_1813_group_pilot2BY1T9_1752001203273_utterances.csv
👉 Copied to: recordings/ready_to_code/20250708_1813_group_pilot2XT15E_1752000324437_utterances.csv
👉 Copied to: recordings/ready_to_code/20250708_1813_group_pilot2XT15E_1752000597133_utterances.csv
👉 Copied to: recordings/ready_to_code/20250708_1813_group_pilot2XT15E_1752000786956_utterances.csv
👉 Copied to: recordings/ready_to_code/20250708_1813_group_pilot2XT15E_1752000924867_utterances.csv
Error processing 1750271953804-6e0b8055-3e36-4c10-b029-5baf6d0be6fb-cam-audio-1750271961404.webm: No columns to parse from file
Error processing 1750271953804-d83b1ff4-a831-4418-9a7c-1cc640ebe4ea-cam-audio-1750271954860.webm: No columns to parse from file
👉 Copied to: recordings/ready_to_code/20250618_1821_group_pilot34BR1P_1750271953804_utterances.csv
Error processing 1750272310917-6af1eeac-be95-4132-82ea-94e332d581de-cam-audio-1750272313591.webm: No columns to parse from file
👉 Copied to: recordings/ready_to_code/20250618_1821_group_pilot34BR1P_1750272310917_utterances.csv
Error processing 1750272633478-fa0ba124-1b9c-42bc-a491-f8a84d23315a-cam-audio-1750272634766.webm: No columns to parse from file
👉 Copied to: recordings/ready_to_code/20250618_1821_group_pilot34BR1P_1750272633478_utterances.csv
Error processing 1750272867424-996ab37a-9593-4e1c-8856-3a0e802d2098-cam-audio-1750272869765.webm: No columns to parse from file
👉 Copied to: recordings/ready_to_code/20250618_1821_group_pilot34BR1P_1750272867424_utterances.csv
👉 Copied to: recordings/ready_to_code/20250618_1821_group_pilot63E4P3_1750271505366_utterances.csv
👉 Copied to: recordings/ready_to_code/20250618_1821_group_pilot63E4P3_1750271804487_utterances.csv
👉 Copied to: recordings/ready_to_code/20250618_1821_group_pilot63E4P3_1750272044099_utterances.csv
👉 Copied to: recordings/ready_to_code/20250618_1821_group_pilot63E4P3_1750272208534_utterances.csv
👉 Copied to: recordings/ready_to_code/20250708_1813_group_pilotAYS7KJ_1751999638506_utterances.csv
👉 Copied to: recordings/ready_to_code/20250708_1813_group_pilotAYS7KJ_1752000054659_utterances.csv
👉 Copied to: recordings/ready_to_code/20250708_1813_group_pilotAYS7KJ_1752000373776_utterances.csv
👉 Copied to: recordings/ready_to_code/20250708_1813_group_pilotAYS7KJ_1752000602122_utterances.csv
👉 Copied to: recordings/ready_to_code/20250618_1821_group_pilotDM261K_1750271899979_utterances.csv
👉 Copied to: recordings/ready_to_code/20250618_1821_group_pilotDM261K_1750272130270_utterances.csv
👉 Copied to: recordings/ready_to_code/20250618_1821_group_pilotDM261K_1750272381421_utterances.csv
👉 Copied to: recordings/ready_to_code/20250618_1821_group_pilotDM261K_1750272545903_utterances.csv
👉 Copied to: recordings/ready_to_code/20250708_1813_group_pilotFTM1KT_1751999637167_utterances.csv
👉 Copied to: recordings/ready_to_code/20250708_1813_group_pilotFTM1KT_1751999887066_utterances.csv
👉 Copied to: recordings/ready_to_code/20250708_1813_group_pilotFTM1KT_1752000165229_utterances.csv
👉 Copied to: recordings/ready_to_code/20250708_1813_group_pilotFTM1KT_1752000368241_utterances.csv
👉 Copied to: recordings/ready_to_code/20250708_1813_group_pilotQ6ZARX_1751999802371_utterances.csv
👉 Copied to: recordings/ready_to_code/20250708_1813_group_pilotQ6ZARX_1752000034101_utterances.csv
👉 Copied to: recordings/ready_to_code/20250708_1813_group_pilotQ6ZARX_1752000227432_utterances.csv
👉 Copied to: recordings/ready_to_code/20250708_1813_group_pilotQ6ZARX_1752000373332_utterances.csv
👉 Copied to: recordings/ready_to_code/20250618_1821_group_pilotRFMEFG_1750271878825_utterances.csv
👉 Copied to: recordings/ready_to_code/20250618_1821_group_pilotRFMEFG_1750272345444_utterances.csv
👉 Copied to: recordings/ready_to_code/20250618_1821_group_pilotRFMEFG_1750272613096_utterances.csv
👉 Copied to: recordings/ready_to_code/20250618_1821_group_pilotRFMEFG_1750272757788_utterances.csv
👉 Copied to: recordings/ready_to_code/20250618_1821_group_pilotRTYG0G_1750271746560_utterances.csv
👉 Copied to: recordings/ready_to_code/20250618_1821_group_pilotRTYG0G_1750272125726_utterances.csv
👉 Copied to: recordings/ready_to_code/20250618_1821_group_pilotRTYG0G_1750272282846_utterances.csv
👉 Copied to: recordings/ready_to_code/20250618_1821_group_pilotRTYG0G_1750272468167_utterances.csv
👉 Copied to: recordings/ready_to_code/20250708_1813_group_pilotTD1HQA_1751999778086_utterances.csv
👉 Copied to: recordings/ready_to_code/20250708_1813_group_pilotTD1HQA_1752000325421_utterances.csv
👉 Copied to: recordings/ready_to_code/20250708_1813_group_pilotTD1HQA_1752000726630_utterances.csv
👉 Copied to: recordings/ready_to_code/20250708_1813_group_pilotTD1HQA_1752000906031_utterances.csv
👉 Copied to: recordings/ready_to_code/20250618_1821_group_pilotTKB9T5_1750272501018_utterances.csv
👉 Copied to: recordings/ready_to_code/20250618_1821_group_pilotTKB9T5_1750273056133_utterances.csv
👉 Copied to: recordings/ready_to_code/20250618_1821_group_pilotTKB9T5_1750273328019_utterances.csv
👉 Copied to: recordings/ready_to_code/20250618_1821_group_pilotTKB9T5_1750273516670_utterances.csv
👉 Copied to: recordings/ready_to_code/20250708_1813_group_pilotVQP5V1_1751999530166_utterances.csv
👉 Copied to: recordings/ready_to_code/20250708_1813_group_pilotVQP5V1_1751999971793_utterances.csv
👉 Copied to: recordings/ready_to_code/20250708_1813_group_pilotVQP5V1_1752000279404_utterances.csv
👉 Copied to: recordings/ready_to_code/20250708_1813_group_pilotVQP5V1_1752000489838_utterances.csv
👉 Copied to: recordings/ready_to_code/20250618_1821_group_pilotXX6T5Y_1750272289727_utterances.csv
👉 Copied to: recordings/ready_to_code/20250618_1821_group_pilotXX6T5Y_1750272704433_utterances.csv
👉 Copied to: recordings/ready_to_code/20250618_1821_group_pilotXX6T5Y_1750273095318_utterances.csv
👉 Copied to: recordings/ready_to_code/20250618_1821_group_pilotXX6T5Y_1750273282311_utterances.csv
👉 Copied to: recordings/ready_to_code/20250618_1821_group_pilotY15NND_1750272110426_utterances.csv
👉 Copied to: recordings/ready_to_code/20250618_1821_group_pilotY15NND_1750272616867_utterances.csv
👉 Copied to: recordings/ready_to_code/20250618_1821_group_pilotY15NND_1750272983235_utterances.csv
👉 Copied to: recordings/ready_to_code/20250618_1821_group_pilotY15NND_1750273191828_utterances.csv
👉 Copied to: recordings/ready_to_code/20250708_1813_group_pilotZN46AE_1751999673688_utterances.csv
👉 Copied to: recordings/ready_to_code/20250708_1813_group_pilotZN46AE_1751999960028_utterances.csv
👉 Copied to: recordings/ready_to_code/20250708_1813_group_pilotZN46AE_1752000233012_utterances.csv
👉 Copied to: recordings/ready_to_code/20250708_1813_group_pilotZN46AE_1752000412233_utterances.csv

In [16]:
conversation_utterances

,raw_start,raw_end,confidence,transcript,filepath_start,filepath_end,timestamp_start,timestamp_end,conversation_id,position
0,0.880000,1.38000,0.948284,hello,1.968000,2.46800,1.928000,2.42800,1752000153821,0
0,2.000000,2.50000,0.655738,oh,3.094000,3.59400,3.045000,3.54500,1752000153821,1
1,3.040000,3.54000,0.994660,okay,4.134000,4.63400,4.085000,4.58500,1752000153821,1
2,5.120000,7.94000,0.979093,so we have to come up with labels for each of ...,6.214000,9.03400,6.165000,8.98500,1752000153821,1
3,11.759999,15.70000,0.981830,so the name should be short easy to remember a...,12.853999,16.79400,12.804999,16.74500,1752000153821,1
...,...,...,...,...,...,...,...,...,...,...
48,256.610020,258.15000,0.945134,and bigger okay,257.704020,259.24400,257.655020,259.19500,1752000153821,1
49,259.010000,261.03000,0.989105,what do you think go to the,260.104000,262.12400,260.055000,262.07500,1752000153821,1
50,261.570000,262.47000,0.974321,go to the quiz,262.664000,263.56400,262.615000,263.51500,1752000153821,1
38,262.624940,264.88495,0.900448,yeah let's go through the quiz good luck,263.712940,265.97295,263.672940,265.93295,1752000153821,0
51,263.810000,266.23000,0.937061,alright let's do it thank you you too,264.904000,267.32400,264.855000,267.27500,1752000153821,1

In [ ]:
# Define the destination folder for finalized files
READY_TO_CODE_DIR = "recordings/ready_to_code"

# Build overall utterances csv for each game
for game_index, group in data.groupby(["group", "mtgStartTime"]):
    conversation_utterances = pd.DataFrame()
    for i, participant in group.iterrows():
        folder = f"{recordings_folder}/{participant['recordingsFolder']}"
        recordingIds = participant["recordingIds"]
        if "missing" in recordingIds: 
            print(f"❌ missing recordings for {participant['recordingsFolder']}")
            continue

        recordingIds = json.loads(participant["recordingIds"].replace("'", '"'))

        files = []
        for i, recordingId in enumerate(recordingIds):
            filesFound = glob.glob(f"{folder}/*{recordingId}*-utterances.csv")
            if len(filesFound) == 0:
                print(f"❌ no files match {recordingId} in folder {participant['recordingsFolder']}")
            elif len(filesFound) > 1:
                # print(f"multiple files found for {recordingId} for {participant['recordingsFolder']}")
                files += filesFound
            else:
                files.append(filesFound[0])

        participant_utterances = pd.DataFrame()
        for file in files:
            try:
                utterances_df = pd.read_csv(file)
                participant_utterances = pd.concat([participant_utterances, utterances_df])
                participant_utterances['file'] = file
            except Exception as e:
                if "No columns to parse from file" in str(e):
                    continue
                print("❌ error in", file, e)
        participant_utterances['conversation_id'] = participant['gameId']
        participant_utterances['position'] = participant['position']
        participant_utterances['speaker'] = participant['deliberationId']
        
        conversation_utterances = pd.concat([conversation_utterances, participant_utterances])
    
    if conversation_utterances.shape[0] == 0:
        print(f"❌ no utterances found for folder {folder}")
        continue

    try:
        conversation_utterances.sort_values(by=['timestamp_start'], inplace=True)
        output_path = f"{folder}/group-utterances.csv"
        conversation_utterances.to_csv(output_path, index=False)

        # Copy the finalized file
        date, time, batch, group_id = folder.split("/")[-1].split("_")
        new_filename = f"{date}_{time}_batch_{batch}_group_{group_id}_game_{group['game'].iloc[0]}_utterances.csv"
        destination_path = os.path.join(READY_TO_CODE_DIR, new_filename)
        shutil.copy(output_path, destination_path)
        print(f"👉 Copied to: {destination_path}")
    except:
        print("problem with recordings", recordingIds)

👉 Copied to: recordings/ready_to_code/20241001_1844_batch_ctt_group_w1V35R4E_game_0_utterances.csv
👉 Copied to: recordings/ready_to_code/20241004_1934_batch_ctt_group_w1M7AWTB_game_1_utterances.csv
👉 Copied to: recordings/ready_to_code/20240923_1531_batch_CTT_group_W1GY0Y4B_game_2_utterances.csv
👉 Copied to: recordings/ready_to_code/20241009_1402_batch_ctt_group_w1K8S0X5_game_3_utterances.csv
👉 Copied to: recordings/ready_to_code/20241001_1844_batch_ctt_group_w1143Q1A_game_4_utterances.csv
👉 Copied to: recordings/ready_to_code/20240920_1732_batch_CT_group_topDE1YJE_game_5_utterances.csv
👉 Copied to: recordings/ready_to_code/20241023_1936_batch_ctt_group_w151PGAV_game_6_utterances.csv
👉 Copied to: recordings/ready_to_code/20241023_1611_batch_ctt_group_w1513W2X_game_7_utterances.csv
👉 Copied to: recordings/ready_to_code/20241001_1844_batch_ctt_group_w1W06WAX_game_8_utterances.csv
👉 Copied to: recordings/ready_to_code/20241028_1752_batch_ctt_group_w16DGSYJ_game_9_utterances.csv
👉 Copied to: recordings/ready_to_code/20241029_1443_batch_ctt_group_w1WZ6Q17_game_10_utterances.csv
👉 Copied to: recordings/ready_to_code/20240926_2049_batch_ctt_group_w1YZYC31_game_11_utterances.csv
👉 Copied to: recordings/ready_to_code/20240919_1914_batch_CT_group_topH7FS3D_game_12_utterances.csv
👉 Copied to: recordings/ready_to_code/20241009_1402_batch_ctt_group_w11GG90A_game_13_utterances.csv
❌ missing recordings for 20241001_1612_ctt_w1Y0RQ1Y
❌ no utterances found for folder recordings/20241001_1612_ctt_w1Y0RQ1Y
👉 Copied to: recordings/ready_to_code/20240930_1406_batch_ctt_group_w1G3ZC1N_game_15_utterances.csv
👉 Copied to: recordings/ready_to_code/20240930_1406_batch_ctt_group_w1GRBV1Z_game_16_utterances.csv
👉 Copied to: recordings/ready_to_code/20241023_1611_batch_ctt_group_w13A7DAW_game_17_utterances.csv
👉 Copied to: recordings/ready_to_code/20241023_1936_batch_ctt_group_w1MZY56D_game_18_utterances.csv
❌ missing recordings for 20241010_1613_ctt_w10GBZDA
👉 Copied to: recordings/ready_to_code/20241010_1613_batch_ctt_group_w10GBZDA_game_19_utterances.csv
👉 Copied to: recordings/ready_to_code/20241024_1823_batch_ctt_group_w12S3EA9_game_20_utterances.csv
👉 Copied to: recordings/ready_to_code/20241028_1752_batch_ctt_group_w1PT2QWF_game_21_utterances.csv
👉 Copied to: recordings/ready_to_code/20240930_1406_batch_ctt_group_w1FPQN5X_game_22_utterances.csv
👉 Copied to: recordings/ready_to_code/20241002_1834_batch_ctt_group_w1GADMJF_game_23_utterances.csv
👉 Copied to: recordings/ready_to_code/20241023_1936_batch_ctt_group_w16G2EPH_game_24_utterances.csv
👉 Copied to: recordings/ready_to_code/20241002_1834_batch_ctt_group_w1PM66E4_game_25_utterances.csv
👉 Copied to: recordings/ready_to_code/20241004_1934_batch_ctt_group_w1GRTFTX_game_26_utterances.csv
👉 Copied to: recordings/ready_to_code/20241023_1611_batch_ctt_group_w10CW30G_game_27_utterances.csv
❌ no files match 172033cf-e9c6-43fa-8342-d5a894a4b48e in folder 20241028_1752_ctt_w1YQBAPR
❌ no files match 17476403-e308-49fb-b6a2-f3f5241e7c9f in folder 20241028_1752_ctt_w1YQBAPR
👉 Copied to: recordings/ready_to_code/20241028_1752_batch_ctt_group_w1YQBAPR_game_28_utterances.csv
👉 Copied to: recordings/ready_to_code/20241002_2139_batch_ctt_group_w1BQX5ZR_game_29_utterances.csv
👉 Copied to: recordings/ready_to_code/20241001_1844_batch_ctt_group_w12NFH38_game_30_utterances.csv
👉 Copied to: recordings/ready_to_code/20240926_1419_batch_ctt_group_w1BA41NG_game_31_utterances.csv
👉 Copied to: recordings/ready_to_code/20240926_1419_batch_ctt_group_w13PSF3X_game_32_utterances.csv
👉 Copied to: recordings/ready_to_code/20241001_1612_batch_ctt_group_w16HAQJ1_game_33_utterances.csv
👉 Copied to: recordings/ready_to_code/20241002_2139_batch_ctt_group_w16K40VN_game_34_utterances.csv
👉 Copied to: recordings/ready_to_code/20241023_1611_batch_ctt_group_w1QM9DHH_game_35_utterances.csv
👉 Copied to: recordings/ready_to_code/20241023_1936_batch_ctt_group_w14SFDKF_game_36_utterances.csv
❌ missing recordings for 20241029_1443_ctt_w1R1GP24
❌ no utterances found for folder recordings/20241029_1443_ctt_w1R1GP24
👉 Copied to: recordings/ready_to_code/20240926_2049_batch_ctt_group_w1WFZCPJ_game_38_utterances.csv
👉 Copied to: recordings/ready_to_code/20241028_1752_batch_ctt_group_w1J9KYQC_game_39_utterances.csv
👉 Copied to: recordings/ready_to_code/20240926_1419_batch_ctt_group_w10E9EMF_game_40_utterances.csv
❌ no files match e6c62ce4-ca22-4e96-9958-c11ba355ef8b in folder 20241023_1936_ctt_w1BFG06W
👉 Copied to: recordings/ready_to_code/20241023_1936_batch_ctt_group_w1BFG06W_game_41_utterances.csv
👉 Copied to: recordings/ready_to_code/20240923_1531_batch_CTT_group_W1RS048T_game_42_utterances.csv
👉 Copied to: recordings/ready_to_code/20241004_1934_batch_ctt_group_w1M5KAHM_game_43_utterances.csv
👉 Copied to: recordings/ready_to_code/20241009_1402_batch_ctt_group_w15HCQPD_game_44_utterances.csv
👉 Copied to: recordings/ready_to_code/20240930_1406_batch_ctt_group_w17JPJ5F_game_45_utterances.csv
👉 Copied to: recordings/ready_to_code/20241001_1612_batch_ctt_group_w142SJTC_game_46_utterances.csv
👉 Copied to: recordings/ready_to_code/20240926_2049_batch_ctt_group_w1QVWEP0_game_47_utterances.csv
👉 Copied to: recordings/ready_to_code/20240930_1406_batch_ctt_group_w1CW1HQV_game_48_utterances.csv
👉 Copied to: recordings/ready_to_code/20241001_1844_batch_ctt_group_w1G5D2TR_game_49_utterances.csv
👉 Copied to: recordings/ready_to_code/20241028_1752_batch_ctt_group_w1793VZP_game_50_utterances.csv
👉 Copied to: recordings/ready_to_code/20240923_1531_batch_CTT_group_W1B2HYZD_game_51_utterances.csv
👉 Copied to: recordings/ready_to_code/20241001_1844_batch_ctt_group_w1GMNJ8N_game_52_utterances.csv
👉 Copied to: recordings/ready_to_code/20241001_1612_batch_ctt_group_w1KXVT2C_game_53_utterances.csv
❌ missing recordings for 20241024_1555_ctt_w135XTQX
👉 Copied to: recordings/ready_to_code/20241024_1555_batch_ctt_group_w135XTQX_game_54_utterances.csv
❌ missing recordings for 20241024_1823_ctt_w1VC7XBZ
❌ no utterances found for folder recordings/20241024_1823_ctt_w1VC7XBZ
👉 Copied to: recordings/ready_to_code/20241028_1752_batch_ctt_group_w10K5J6R_game_56_utterances.csv
👉 Copied to: recordings/ready_to_code/20241001_1844_batch_ctt_group_w1EKPQQM_game_57_utterances.csv
👉 Copied to: recordings/ready_to_code/20241002_2139_batch_ctt_group_w18ES3HJ_game_58_utterances.csv
👉 Copied to: recordings/ready_to_code/20240930_1406_batch_ctt_group_w1S01724_game_59_utterances.csv
👉 Copied to: recordings/ready_to_code/20241004_1934_batch_ctt_group_w1DE297H_game_60_utterances.csv
👉 Copied to: recordings/ready_to_code/20240926_1419_batch_ctt_group_w186EDTB_game_61_utterances.csv
❌ no utterances found for folder recordings/20241002_2139_ctt_w15B9MHQ
👉 Copied to: recordings/ready_to_code/20241023_1936_batch_ctt_group_w1EH90QH_game_63_utterances.csv
👉 Copied to: recordings/ready_to_code/20240926_1419_batch_ctt_group_w177WH3H_game_64_utterances.csv
👉 Copied to: recordings/ready_to_code/20241002_1834_batch_ctt_group_w1ERGTXK_game_65_utterances.csv
👉 Copied to: recordings/ready_to_code/20241023_1936_batch_ctt_group_w1FNMZX4_game_66_utterances.csv
👉 Copied to: recordings/ready_to_code/20241002_1834_batch_ctt_group_w1KF0QN8_game_67_utterances.csv
❌ missing recordings for 20240926_2049_ctt_w1WAJ77J
👉 Copied to: recordings/ready_to_code/20240926_2049_batch_ctt_group_w1WAJ77J_game_68_utterances.csv
👉 Copied to: recordings/ready_to_code/20241001_1844_batch_ctt_group_w1QY4W5F_game_69_utterances.csv
👉 Copied to: recordings/ready_to_code/20240923_1531_batch_CTT_group_W1S2G97A_game_70_utterances.csv
👉 Copied to: recordings/ready_to_code/20241001_1612_batch_ctt_group_w14Q3ZBK_game_71_utterances.csv
👉 Copied to: recordings/ready_to_code/20241010_1613_batch_ctt_group_w161Z2ZS_game_72_utterances.csv
👉 Copied to: recordings/ready_to_code/20241004_1934_batch_ctt_group_w1QGZVVV_game_73_utterances.csv
👉 Copied to: recordings/ready_to_code/20241028_1752_batch_ctt_group_w1TT3ZQF_game_74_utterances.csv
👉 Copied to: recordings/ready_to_code/20240923_1531_batch_CTT_group_W1GV2488_game_75_utterances.csv
❌ no utterances found for folder recordings/20241004_1934_ctt_w1P5FN67
👉 Copied to: recordings/ready_to_code/20241028_1752_batch_ctt_group_w15NYG7J_game_77_utterances.csv
👉 Copied to: recordings/ready_to_code/20241001_1844_batch_ctt_group_w1ZN9C4K_game_78_utterances.csv
👉 Copied to: recordings/ready_to_code/20240920_1732_batch_CT_group_topMWAGR8_game_79_utterances.csv
👉 Copied to: recordings/ready_to_code/20240930_1406_batch_ctt_group_w1EG2HPK_game_80_utterances.csv
👉 Copied to: recordings/ready_to_code/20241009_1402_batch_ctt_group_w1PSGC4A_game_81_utterances.csv
👉 Copied to: recordings/ready_to_code/20241029_1443_batch_ctt_group_w13MRB85_game_82_utterances.csv
👉 Copied to: recordings/ready_to_code/20241023_1611_batch_ctt_group_w1S6NHW5_game_83_utterances.csv
👉 Copied to: recordings/ready_to_code/20240923_1531_batch_CTT_group_W1F6JV7K_game_84_utterances.csv
👉 Copied to: recordings/ready_to_code/20241001_1844_batch_ctt_group_w118039V_game_85_utterances.csv
👉 Copied to: recordings/ready_to_code/20241002_1834_batch_ctt_group_w1D6VE2S_game_86_utterances.csv
👉 Copied to: recordings/ready_to_code/20241023_1611_batch_ctt_group_w1J3WF4R_game_87_utterances.csv
👉 Copied to: recordings/ready_to_code/20241009_1402_batch_ctt_group_w1WHVADR_game_88_utterances.csv
👉 Copied to: recordings/ready_to_code/20241007_1905_batch_ctt_group_w1WWWH1A_game_89_utterances.csv
👉 Copied to: recordings/ready_to_code/20241009_1402_batch_ctt_group_w1JXTYFB_game_90_utterances.csv
❌ no utterances found for folder recordings/20240930_1406_ctt_w1KN891H
👉 Copied to: recordings/ready_to_code/20241002_1834_batch_ctt_group_w1Z78HC7_game_92_utterances.csv
👉 Copied to: recordings/ready_to_code/20241002_2139_batch_ctt_group_w1D5CBGP_game_93_utterances.csv
👉 Copied to: recordings/ready_to_code/20241023_1611_batch_ctt_group_w11BGNH5_game_94_utterances.csv
👉 Copied to: recordings/ready_to_code/20241023_1611_batch_ctt_group_w1JM1GY8_game_95_utterances.csv
👉 Copied to: recordings/ready_to_code/20241029_1443_batch_ctt_group_w1QWTZ84_game_96_utterances.csv
❌ missing recordings for 20241002_2139_ctt_w15ZSBPE
❌ no utterances found for folder recordings/20241002_2139_ctt_w15ZSBPE
👉 Copied to: recordings/ready_to_code/20241010_1613_batch_ctt_group_w132SC1R_game_98_utterances.csv
👉 Copied to: recordings/ready_to_code/20240926_2049_batch_ctt_group_w1SZVCS1_game_99_utterances.csv
👉 Copied to: recordings/ready_to_code/20241023_1936_batch_ctt_group_w1DPZPJQ_game_100_utterances.csv
👉 Copied to: recordings/ready_to_code/20241029_1443_batch_ctt_group_w15G16J5_game_101_utterances.csv
❌ no files match 81c03fdf-af93-49e4-bc5a-6d70b4575245 in folder 20240930_1406_ctt_w1XJW966
👉 Copied to: recordings/ready_to_code/20240930_1406_batch_ctt_group_w1XJW966_game_102_utterances.csv
👉 Copied to: recordings/ready_to_code/20241002_2139_batch_ctt_group_w1KTYKB2_game_103_utterances.csv
👉 Copied to: recordings/ready_to_code/20241001_1844_batch_ctt_group_w1D14B4N_game_104_utterances.csv
👉 Copied to: recordings/ready_to_code/20241002_2139_batch_ctt_group_w16S8WSX_game_105_utterances.csv
👉 Copied to: recordings/ready_to_code/20241023_1611_batch_ctt_group_w1ZGPERF_game_106_utterances.csv
👉 Copied to: recordings/ready_to_code/20241029_1443_batch_ctt_group_w1C6VDQD_game_107_utterances.csv
👉 Copied to: recordings/ready_to_code/20241002_1834_batch_ctt_group_w1NBBKXN_game_108_utterances.csv
👉 Copied to: recordings/ready_to_code/20241024_1555_batch_ctt_group_w1JW5CYX_game_109_utterances.csv
👉 Copied to: recordings/ready_to_code/20241024_1823_batch_ctt_group_w13EJKNT_game_110_utterances.csv
👉 Copied to: recordings/ready_to_code/20240923_1531_batch_CTT_group_W1KQKTMQ_game_111_utterances.csv
👉 Copied to: recordings/ready_to_code/20241002_1834_batch_ctt_group_w1R4YE3K_game_112_utterances.csv
👉 Copied to: recordings/ready_to_code/20241023_1611_batch_ctt_group_w13YY4JE_game_113_utterances.csv
👉 Copied to: recordings/ready_to_code/20241009_1402_batch_ctt_group_w1Z3WSK0_game_114_utterances.csv
❌ no files match b361bb6a-bf63-482e-9db6-b5b619e2336a in folder 20241023_1611_ctt_w1ZK82MK
❌ no files match 074d3a33-2e79-44b3-9047-30612b6199f5 in folder 20241023_1611_ctt_w1ZK82MK
❌ no files match 39df55a9-3388-4f46-906e-54a4d139fdd4 in folder 20241023_1611_ctt_w1ZK82MK
👉 Copied to: recordings/ready_to_code/20241023_1611_batch_ctt_group_w1ZK82MK_game_115_utterances.csv
👉 Copied to: recordings/ready_to_code/20241002_1834_batch_ctt_group_w1XXG21B_game_116_utterances.csv
👉 Copied to: recordings/ready_to_code/20241023_1611_batch_ctt_group_w1QKRWR5_game_117_utterances.csv
👉 Copied to: recordings/ready_to_code/20241002_2139_batch_ctt_group_w1VX5SDK_game_118_utterances.csv
👉 Copied to: recordings/ready_to_code/20241009_1402_batch_ctt_group_w1C3XZZP_game_119_utterances.csv
👉 Copied to: recordings/ready_to_code/20241002_2139_batch_ctt_group_w1DD4FSV_game_120_utterances.csv
👉 Copied to: recordings/ready_to_code/20241001_1844_batch_ctt_group_w1D0JTPP_game_121_utterances.csv
👉 Copied to: recordings/ready_to_code/20240930_1406_batch_ctt_group_w1DX9HBX_game_122_utterances.csv
👉 Copied to: recordings/ready_to_code/20241009_1402_batch_ctt_group_w1V33MYT_game_123_utterances.csv
👉 Copied to: recordings/ready_to_code/20240923_1531_batch_CTT_group_W1FVP9QY_game_124_utterances.csv
👉 Copied to: recordings/ready_to_code/20241024_1555_batch_ctt_group_w1D55SEM_game_125_utterances.csv
👉 Copied to: recordings/ready_to_code/20240920_1732_batch_CT_group_topFDAGM1_game_126_utterances.csv
👉 Copied to: recordings/ready_to_code/20240926_1419_batch_ctt_group_w1VYDY3G_game_127_utterances.csv
👉 Copied to: recordings/ready_to_code/20241001_1612_batch_ctt_group_w1Z7GFPS_game_128_utterances.csv
👉 Copied to: recordings/ready_to_code/20241028_1752_batch_ctt_group_w1EBT647_game_129_utterances.csv
👉 Copied to: recordings/ready_to_code/20241024_1823_batch_ctt_group_w1MZY9FQ_game_130_utterances.csv
👉 Copied to: recordings/ready_to_code/20240919_1914_batch_CT_group_topQH79YQ_game_131_utterances.csv
👉 Copied to: recordings/ready_to_code/20241001_1612_batch_ctt_group_w19NE4NE_game_132_utterances.csv
👉 Copied to: recordings/ready_to_code/20241001_1612_batch_ctt_group_w1X6BADF_game_133_utterances.csv
👉 Copied to: recordings/ready_to_code/20241002_2139_batch_ctt_group_w1WVWN5J_game_134_utterances.csv
👉 Copied to: recordings/ready_to_code/20240926_2049_batch_ctt_group_w1HB0GQK_game_135_utterances.csv
❌ missing recordings for 20241023_1611_ctt_w13W6JBZ
❌ no utterances found for folder recordings/20241023_1611_ctt_w13W6JBZ
👉 Copied to: recordings/ready_to_code/20241023_1936_batch_ctt_group_w11KWVV5_game_137_utterances.csv
👉 Copied to: recordings/ready_to_code/20241001_1844_batch_ctt_group_w1AQNXWH_game_138_utterances.csv
👉 Copied to: recordings/ready_to_code/20240926_2049_batch_ctt_group_w11MY1BD_game_139_utterances.csv
👉 Copied to: recordings/ready_to_code/20241023_1936_batch_ctt_group_w1BMVN5X_game_140_utterances.csv
❌ missing recordings for 20240926_2049_ctt_w1N3N7XB
❌ no utterances found for folder recordings/20240926_2049_ctt_w1N3N7XB
👉 Copied to: recordings/ready_to_code/20240930_1406_batch_ctt_group_w1817ZF4_game_142_utterances.csv
👉 Copied to: recordings/ready_to_code/20240923_1531_batch_CTT_group_W1X5743V_game_143_utterances.csv
👉 Copied to: recordings/ready_to_code/20240926_2049_batch_ctt_group_w1BGH99F_game_144_utterances.csv
👉 Copied to: recordings/ready_to_code/20241001_1844_batch_ctt_group_w1JZWK20_game_145_utterances.csv
👉 Copied to: recordings/ready_to_code/20241029_1443_batch_ctt_group_w17143VQ_game_146_utterances.csv
👉 Copied to: recordings/ready_to_code/20241023_1611_batch_ctt_group_w1ZHPTRE_game_147_utterances.csv
👉 Copied to: recordings/ready_to_code/20241029_1443_batch_ctt_group_w1DSQDE6_game_148_utterances.csv
👉 Copied to: recordings/ready_to_code/20240919_1914_batch_CT_group_top0EEWMB_game_149_utterances.csv
👉 Copied to: recordings/ready_to_code/20241023_1936_batch_ctt_group_w1MX62EK_game_150_utterances.csv
👉 Copied to: recordings/ready_to_code/20240923_1531_batch_CTT_group_W1G9CNMR_game_151_utterances.csv
👉 Copied to: recordings/ready_to_code/20241028_1752_batch_ctt_group_w1HD9DVR_game_152_utterances.csv
👉 Copied to: recordings/ready_to_code/20241001_1844_batch_ctt_group_w17AYN1J_game_153_utterances.csv
👉 Copied to: recordings/ready_to_code/20241002_1834_batch_ctt_group_w1ZHWQ0Z_game_154_utterances.csv
👉 Copied to: recordings/ready_to_code/20240930_1406_batch_ctt_group_w1AEYH5J_game_155_utterances.csv
❌ no files match 48bd21ee-6eb4-48bc-b528-d972d82fa9f9 in folder 20241024_1823_ctt_w1R86FBP
❌ no files match 0f2068c1-5817-46e0-9950-e83c87074bec in folder 20241024_1823_ctt_w1R86FBP
❌ no files match d52c0721-5e5c-48ba-b201-5d864f797f39 in folder 20241024_1823_ctt_w1R86FBP
❌ no files match 1b6ba4cd-6366-4280-91c9-50f57f83a028 in folder 20241024_1823_ctt_w1R86FBP
❌ no files match 9007aeff-16d3-4de1-b458-9662241b3953 in folder 20241024_1823_ctt_w1R86FBP
❌ no files match 55642d19-116e-4c5e-b1fe-ccc816de59be in folder 20241024_1823_ctt_w1R86FBP
❌ no files match c84d3d38-831c-402d-bb24-a0b20f0b7e07 in folder 20241024_1823_ctt_w1R86FBP
👉 Copied to: recordings/ready_to_code/20241024_1823_batch_ctt_group_w1R86FBP_game_156_utterances.csv
👉 Copied to: recordings/ready_to_code/20241004_1934_batch_ctt_group_w1P12WK2_game_157_utterances.csv
👉 Copied to: recordings/ready_to_code/20240930_1406_batch_ctt_group_w1T6JFV0_game_158_utterances.csv
❌ no files match 70a7660d-5567-4328-b8c9-fc1571554973 in folder 20241001_1612_ctt_w1ZZ2FXZ
❌ no files match 6eea2019-0aea-4a64-9a30-595e937c377e in folder 20241001_1612_ctt_w1ZZ2FXZ
👉 Copied to: recordings/ready_to_code/20241001_1612_batch_ctt_group_w1ZZ2FXZ_game_159_utterances.csv
👉 Copied to: recordings/ready_to_code/20241010_1613_batch_ctt_group_w1E4304K_game_160_utterances.csv
👉 Copied to: recordings/ready_to_code/20241023_1936_batch_ctt_group_w14D5HJR_game_161_utterances.csv
👉 Copied to: recordings/ready_to_code/20241023_1936_batch_ctt_group_w15GQ30H_game_162_utterances.csv
👉 Copied to: recordings/ready_to_code/20241001_1844_batch_ctt_group_w1B97P8E_game_163_utterances.csv
👉 Copied to: recordings/ready_to_code/20240920_1732_batch_CT_group_topZ4A8NH_game_164_utterances.csv
👉 Copied to: recordings/ready_to_code/20240920_1732_batch_CT_group_topRPP2H3_game_165_utterances.csv
👉 Copied to: recordings/ready_to_code/20240923_1531_batch_CTT_group_W1GV6XGW_game_166_utterances.csv
👉 Copied to: recordings/ready_to_code/20241029_1443_batch_ctt_group_w143ZS1Q_game_167_utterances.csv
👉 Copied to: recordings/ready_to_code/20241004_1934_batch_ctt_group_w165RGQX_game_168_utterances.csv
👉 Copied to: recordings/ready_to_code/20240926_1419_batch_ctt_group_w17Y17YA_game_169_utterances.csv
👉 Copied to: recordings/ready_to_code/20241001_1612_batch_ctt_group_w1M9R85X_game_170_utterances.csv
❌ missing recordings for 20241001_1844_ctt_w16XX7H1
❌ no files match 4fbb0627-6b19-4cac-9e00-26d0059b2f6d in folder 20241001_1844_ctt_w16XX7H1
❌ no files match 4dc8edf2-b68a-4e56-b151-d98ed8b6e5d1 in folder 20241001_1844_ctt_w16XX7H1
❌ no files match 065153e5-b646-49dd-a934-2a368f7b23ca in folder 20241001_1844_ctt_w16XX7H1
👉 Copied to: recordings/ready_to_code/20241001_1844_batch_ctt_group_w16XX7H1_game_171_utterances.csv
👉 Copied to: recordings/ready_to_code/20241002_2139_batch_ctt_group_w1ESS1MV_game_172_utterances.csv
👉 Copied to: recordings/ready_to_code/20241024_1823_batch_ctt_group_w1BPHHH5_game_173_utterances.csv
👉 Copied to: recordings/ready_to_code/20241002_1834_batch_ctt_group_w1RP2BXN_game_174_utterances.csv
👉 Copied to: recordings/ready_to_code/20241007_1905_batch_ctt_group_w1EX4KXB_game_175_utterances.csv
👉 Copied to: recordings/ready_to_code/20241028_1752_batch_ctt_group_w1AFS03N_game_176_utterances.csv
👉 Copied to: recordings/ready_to_code/20241009_1402_batch_ctt_group_w15BXHRP_game_177_utterances.csv
❌ missing recordings for 20240930_1406_ctt_w1R9X0HM

# Compile words csv for each game

In [36]:
READY_TO_CODE_DIR = "recordings/ready_to_code"

# build overall words csv for each game
for game_index, group in data.groupby("game"):
    # try:
        conversation_words = pd.DataFrame()
        for i, participant in group.iterrows():
            folder = f"{recordings_folder}/{participant['recordingsFolder']}"
            raw_recordingIds = participant["recordingIds"]
            if "missing" in raw_recordingIds:
                print("❌ missing in", folder)
                continue
            recordingIds = json.loads(participant["recordingIds"].replace("'", '"'))
            
            files = []
            for recordingId in recordingIds:
                glob_files = glob.glob(f"{folder}/*{recordingId}*-words.csv")
                if len(glob_files) == 0:
                    print(f"❌ no files match {recordingId} in folder {participant['recordingsFolder']}")
                elif len(glob_files) > 1:
                    print(f"❌ multiple files found for {recordingId} for {participant['recordingsFolder']}")
                else:
                    files.append(glob_files[0])

            # files = [glob.glob(f"{folder}/*{recordingId}*-words.csv")[0] for recordingId in recordingIds]
            participant_words = pd.DataFrame()
            for file in files:
                try:
                    words_df = pd.read_csv(file)
                    participant_words = pd.concat([participant_words, words_df])
                    participant_words['file'] = file
                except:
                    print("❌ error in", file)
            participant_words['conversation_id'] = participant['gameId']
            participant_words['position'] = participant['position']
            
            conversation_words = pd.concat([conversation_words, participant_words])

        if conversation_words.shape[0] == 0:
            print("❌ no words in", folder)
            continue
        conversation_words.sort_values(by=['timestamp_start'], inplace=True)

        output_path = f"{folder}/group-words.csv"
        conversation_words.to_csv(output_path, index=False)
        print("✅", folder)

        # Copy the finalized file
        date, time, batch, group_id = folder.split("/")[-1].split("_")
        new_filename = f"{date}_{time}_batch_{batch}_group_{group_id}_game_{group['game'].iloc[0]}_words.csv"
        destination_path = os.path.join(READY_TO_CODE_DIR, new_filename)
        shutil.copy(output_path, destination_path)
        print(f"👉 Copied to: {destination_path}")
    # except Exception as e:
        # print("error in", folder, e)
        # print("❌", folder)
        # break

✅ recordings/20241001_1844_ctt_w1V35R4E
👉 Copied to: recordings/ready_to_code/20241001_1844_batch_ctt_group_w1V35R4E_game_0_words.csv
✅ recordings/20241004_1934_ctt_w1M7AWTB
👉 Copied to: recordings/ready_to_code/20241004_1934_batch_ctt_group_w1M7AWTB_game_1_words.csv
❌ no files match a1efd28a-af9d-4217-b785-204f7547f268 in folder 20240923_1531_CTT_W1GY0Y4B
✅ recordings/20240923_1531_CTT_W1GY0Y4B
👉 Copied to: recordings/ready_to_code/20240923_1531_batch_CTT_group_W1GY0Y4B_game_2_words.csv
✅ recordings/20241009_1402_ctt_w1K8S0X5
👉 Copied to: recordings/ready_to_code/20241009_1402_batch_ctt_group_w1K8S0X5_game_3_words.csv
✅ recordings/20241001_1844_ctt_w1143Q1A
👉 Copied to: recordings/ready_to_code/20241001_1844_batch_ctt_group_w1143Q1A_game_4_words.csv
✅ recordings/20240920_1732_CT_topDE1YJE
👉 Copied to: recordings/ready_to_code/20240920_1732_batch_CT_group_topDE1YJE_game_5_words.csv
✅ recordings/20241023_1936_ctt_w151PGAV
👉 Copied to: recordings/ready_to_code/20241023_1936_batch_ctt_group_w151PGAV_game_6_words.csv
✅ recordings/20241023_1611_ctt_w1513W2X
👉 Copied to: recordings/ready_to_code/20241023_1611_batch_ctt_group_w1513W2X_game_7_words.csv
✅ recordings/20241001_1844_ctt_w1W06WAX
👉 Copied to: recordings/ready_to_code/20241001_1844_batch_ctt_group_w1W06WAX_game_8_words.csv
❌ no files match e659d293-47f7-4080-8340-f77d673eef1b in folder 20241028_1752_ctt_w16DGSYJ
✅ recordings/20241028_1752_ctt_w16DGSYJ
👉 Copied to: recordings/ready_to_code/20241028_1752_batch_ctt_group_w16DGSYJ_game_9_words.csv
✅ recordings/20241029_1443_ctt_w1WZ6Q17
👉 Copied to: recordings/ready_to_code/20241029_1443_batch_ctt_group_w1WZ6Q17_game_10_words.csv
✅ recordings/20240926_2049_ctt_w1YZYC31
👉 Copied to: recordings/ready_to_code/20240926_2049_batch_ctt_group_w1YZYC31_game_11_words.csv
✅ recordings/20240919_1914_CT_topH7FS3D
👉 Copied to: recordings/ready_to_code/20240919_1914_batch_CT_group_topH7FS3D_game_12_words.csv
✅ recordings/20241009_1402_ctt_w11GG90A
👉 Copied to: recordings/ready_to_code/20241009_1402_batch_ctt_group_w11GG90A_game_13_words.csv
❌ no files match 1cd4f28b-4338-4e46-abc1-20ab46329ea6 in folder 20241001_1612_ctt_w1Y0RQ1Y
❌ missing in recordings/20241001_1612_ctt_w1Y0RQ1Y
❌ no words in recordings/20241001_1612_ctt_w1Y0RQ1Y
✅ recordings/20240930_1406_ctt_w1G3ZC1N
👉 Copied to: recordings/ready_to_code/20240930_1406_batch_ctt_group_w1G3ZC1N_game_15_words.csv
✅ recordings/20240930_1406_ctt_w1GRBV1Z
👉 Copied to: recordings/ready_to_code/20240930_1406_batch_ctt_group_w1GRBV1Z_game_16_words.csv
❌ no files match 1de3ef7a-3073-443c-ae36-f8403adebf15 in folder 20241023_1611_ctt_w13A7DAW
✅ recordings/20241023_1611_ctt_w13A7DAW
👉 Copied to: recordings/ready_to_code/20241023_1611_batch_ctt_group_w13A7DAW_game_17_words.csv
✅ recordings/20241023_1936_ctt_w1MZY56D
👉 Copied to: recordings/ready_to_code/20241023_1936_batch_ctt_group_w1MZY56D_game_18_words.csv
❌ missing in recordings/20241010_1613_ctt_w10GBZDA
✅ recordings/20241010_1613_ctt_w10GBZDA
👉 Copied to: recordings/ready_to_code/20241010_1613_batch_ctt_group_w10GBZDA_game_19_words.csv
✅ recordings/20241024_1823_ctt_w12S3EA9
👉 Copied to: recordings/ready_to_code/20241024_1823_batch_ctt_group_w12S3EA9_game_20_words.csv
✅ recordings/20241028_1752_ctt_w1PT2QWF
👉 Copied to: recordings/ready_to_code/20241028_1752_batch_ctt_group_w1PT2QWF_game_21_words.csv
✅ recordings/20240930_1406_ctt_w1FPQN5X
👉 Copied to: recordings/ready_to_code/20240930_1406_batch_ctt_group_w1FPQN5X_game_22_words.csv
✅ recordings/20241002_1834_ctt_w1GADMJF
👉 Copied to: recordings/ready_to_code/20241002_1834_batch_ctt_group_w1GADMJF_game_23_words.csv
✅ recordings/20241023_1936_ctt_w16G2EPH
👉 Copied to: recordings/ready_to_code/20241023_1936_batch_ctt_group_w16G2EPH_game_24_words.csv
✅ recordings/20241002_1834_ctt_w1PM66E4
👉 Copied to: recordings/ready_to_code/20241002_1834_batch_ctt_group_w1PM66E4_game_25_words.csv
✅ recordings/20241004_1934_ctt_w1GRTFTX
👉 Copied to: recordings/ready_to_code/20241004_1934_batch_ctt_group_w1GRTFTX_game_26_words.csv
✅ recordings/20241023_1611_ctt_w10CW30G
👉 Copied to: recordings/ready_to_code/20241023_1611_batch_ctt_group_w10CW30G_game_27_words.csv
❌ no files match 172033cf-e9c6-43fa-8342-d5a894a4b48e in folder 20241028_1752_ctt_w1YQBAPR
❌ no files match 17476403-e308-49fb-b6a2-f3f5241e7c9f in folder 20241028_1752_ctt_w1YQBAPR
❌ no files match d5728963-a221-4816-a7ec-56e96741e4c8 in folder 20241028_1752_ctt_w1YQBAPR
✅ recordings/20241028_1752_ctt_w1YQBAPR
👉 Copied to: recordings/ready_to_code/20241028_1752_batch_ctt_group_w1YQBAPR_game_28_words.csv
✅ recordings/20241002_2139_ctt_w1BQX5ZR
👉 Copied to: recordings/ready_to_code/20241002_2139_batch_ctt_group_w1BQX5ZR_game_29_words.csv
✅ recordings/20241001_1844_ctt_w12NFH38
👉 Copied to: recordings/ready_to_code/20241001_1844_batch_ctt_group_w12NFH38_game_30_words.csv
✅ recordings/20240926_1419_ctt_w1BA41NG
👉 Copied to: recordings/ready_to_code/20240926_1419_batch_ctt_group_w1BA41NG_game_31_words.csv
✅ recordings/20240926_1419_ctt_w13PSF3X
👉 Copied to: recordings/ready_to_code/20240926_1419_batch_ctt_group_w13PSF3X_game_32_words.csv
✅ recordings/20241001_1612_ctt_w16HAQJ1
👉 Copied to: recordings/ready_to_code/20241001_1612_batch_ctt_group_w16HAQJ1_game_33_words.csv
✅ recordings/20241002_2139_ctt_w16K40VN
👉 Copied to: recordings/ready_to_code/20241002_2139_batch_ctt_group_w16K40VN_game_34_words.csv
❌ no files match 93a660fa-b5a8-4484-9dc0-31310b473685 in folder 20241023_1611_ctt_w1QM9DHH
✅ recordings/20241023_1611_ctt_w1QM9DHH
👉 Copied to: recordings/ready_to_code/20241023_1611_batch_ctt_group_w1QM9DHH_game_35_words.csv
✅ recordings/20241023_1936_ctt_w14SFDKF
👉 Copied to: recordings/ready_to_code/20241023_1936_batch_ctt_group_w14SFDKF_game_36_words.csv
❌ missing in recordings/20241029_1443_ctt_w1R1GP24
❌ no files match 3b6e1513-3123-4345-a4f4-63fd2d336431 in folder 20241029_1443_ctt_w1R1GP24
❌ no words in recordings/20241029_1443_ctt_w1R1GP24
✅ recordings/20240926_2049_ctt_w1WFZCPJ
👉 Copied to: recordings/ready_to_code/20240926_2049_batch_ctt_group_w1WFZCPJ_game_38_words.csv
✅ recordings/20241028_1752_ctt_w1J9KYQC
👉 Copied to: recordings/ready_to_code/20241028_1752_batch_ctt_group_w1J9KYQC_game_39_words.csv
✅ recordings/20240926_1419_ctt_w10E9EMF
👉 Copied to: recordings/ready_to_code/20240926_1419_batch_ctt_group_w10E9EMF_game_40_words.csv
❌ no files match e6c62ce4-ca22-4e96-9958-c11ba355ef8b in folder 20241023_1936_ctt_w1BFG06W
✅ recordings/20241023_1936_ctt_w1BFG06W
👉 Copied to: recordings/ready_to_code/20241023_1936_batch_ctt_group_w1BFG06W_game_41_words.csv
✅ recordings/20240923_1531_CTT_W1RS048T
👉 Copied to: recordings/ready_to_code/20240923_1531_batch_CTT_group_W1RS048T_game_42_words.csv
✅ recordings/20241004_1934_ctt_w1M5KAHM
👉 Copied to: recordings/ready_to_code/20241004_1934_batch_ctt_group_w1M5KAHM_game_43_words.csv
✅ recordings/20241009_1402_ctt_w15HCQPD
👉 Copied to: recordings/ready_to_code/20241009_1402_batch_ctt_group_w15HCQPD_game_44_words.csv
✅ recordings/20240930_1406_ctt_w17JPJ5F
👉 Copied to: recordings/ready_to_code/20240930_1406_batch_ctt_group_w17JPJ5F_game_45_words.csv
✅ recordings/20241001_1612_ctt_w142SJTC
👉 Copied to: recordings/ready_to_code/20241001_1612_batch_ctt_group_w142SJTC_game_46_words.csv
✅ recordings/20240926_2049_ctt_w1QVWEP0
👉 Copied to: recordings/ready_to_code/20240926_2049_batch_ctt_group_w1QVWEP0_game_47_words.csv
✅ recordings/20240930_1406_ctt_w1CW1HQV
👉 Copied to: recordings/ready_to_code/20240930_1406_batch_ctt_group_w1CW1HQV_game_48_words.csv
✅ recordings/20241001_1844_ctt_w1G5D2TR
👉 Copied to: recordings/ready_to_code/20241001_1844_batch_ctt_group_w1G5D2TR_game_49_words.csv
✅ recordings/20241028_1752_ctt_w1793VZP
👉 Copied to: recordings/ready_to_code/20241028_1752_batch_ctt_group_w1793VZP_game_50_words.csv
✅ recordings/20240923_1531_CTT_W1B2HYZD
👉 Copied to: recordings/ready_to_code/20240923_1531_batch_CTT_group_W1B2HYZD_game_51_words.csv
✅ recordings/20241001_1844_ctt_w1GMNJ8N
👉 Copied to: recordings/ready_to_code/20241001_1844_batch_ctt_group_w1GMNJ8N_game_52_words.csv
✅ recordings/20241001_1612_ctt_w1KXVT2C
👉 Copied to: recordings/ready_to_code/20241001_1612_batch_ctt_group_w1KXVT2C_game_53_words.csv
❌ missing in recordings/20241024_1555_ctt_w135XTQX
✅ recordings/20241024_1555_ctt_w135XTQX
👉 Copied to: recordings/ready_to_code/20241024_1555_batch_ctt_group_w135XTQX_game_54_words.csv
❌ no files match 2f952834-74d0-4591-a8cb-6af6851cd61f in folder 20241024_1823_ctt_w1VC7XBZ
❌ missing in recordings/20241024_1823_ctt_w1VC7XBZ
❌ no words in recordings/20241024_1823_ctt_w1VC7XBZ
✅ recordings/20241028_1752_ctt_w10K5J6R
👉 Copied to: recordings/ready_to_code/20241028_1752_batch_ctt_group_w10K5J6R_game_56_words.csv
✅ recordings/20241001_1844_ctt_w1EKPQQM
👉 Copied to: recordings/ready_to_code/20241001_1844_batch_ctt_group_w1EKPQQM_game_57_words.csv
✅ recordings/20241002_2139_ctt_w18ES3HJ
👉 Copied to: recordings/ready_to_code/20241002_2139_batch_ctt_group_w18ES3HJ_game_58_words.csv
✅ recordings/20240930_1406_ctt_w1S01724
👉 Copied to: recordings/ready_to_code/20240930_1406_batch_ctt_group_w1S01724_game_59_words.csv
❌ no files match 9b6225c4-4d95-4078-9ebf-02955dc3964b in folder 20241004_1934_ctt_w1DE297H
✅ recordings/20241004_1934_ctt_w1DE297H
👉 Copied to: recordings/ready_to_code/20241004_1934_batch_ctt_group_w1DE297H_game_60_words.csv
✅ recordings/20240926_1419_ctt_w186EDTB
👉 Copied to: recordings/ready_to_code/20240926_1419_batch_ctt_group_w186EDTB_game_61_words.csv
❌ no files match c6ebffd7-5752-438f-8f2c-e53d1160b9aa in folder 20241002_2139_ctt_w15B9MHQ
❌ no files match b7d198d7-8f76-4986-a0ad-1975470682c6 in folder 20241002_2139_ctt_w15B9MHQ
❌ no words in recordings/20241002_2139_ctt_w15B9MHQ
✅ recordings/20241023_1936_ctt_w1EH90QH
👉 Copied to: recordings/ready_to_code/20241023_1936_batch_ctt_group_w1EH90QH_game_63_words.csv
✅ recordings/20240926_1419_ctt_w177WH3H
👉 Copied to: recordings/ready_to_code/20240926_1419_batch_ctt_group_w177WH3H_game_64_words.csv
✅ recordings/20241002_1834_ctt_w1ERGTXK
👉 Copied to: recordings/ready_to_code/20241002_1834_batch_ctt_group_w1ERGTXK_game_65_words.csv
✅ recordings/20241023_1936_ctt_w1FNMZX4
👉 Copied to: recordings/ready_to_code/20241023_1936_batch_ctt_group_w1FNMZX4_game_66_words.csv
✅ recordings/20241002_1834_ctt_w1KF0QN8
👉 Copied to: recordings/ready_to_code/20241002_1834_batch_ctt_group_w1KF0QN8_game_67_words.csv
❌ missing in recordings/20240926_2049_ctt_w1WAJ77J
✅ recordings/20240926_2049_ctt_w1WAJ77J
👉 Copied to: recordings/ready_to_code/20240926_2049_batch_ctt_group_w1WAJ77J_game_68_words.csv
✅ recordings/20241001_1844_ctt_w1QY4W5F
👉 Copied to: recordings/ready_to_code/20241001_1844_batch_ctt_group_w1QY4W5F_game_69_words.csv
❌ no files match 5a8fced7-0ed6-4073-b85d-6a284ae54066 in folder 20240923_1531_CTT_W1S2G97A
✅ recordings/20240923_1531_CTT_W1S2G97A
👉 Copied to: recordings/ready_to_code/20240923_1531_batch_CTT_group_W1S2G97A_game_70_words.csv
❌ no files match e84dda3f-9dc7-4f44-a0a0-8307dbd40f53 in folder 20241001_1612_ctt_w14Q3ZBK
✅ recordings/20241001_1612_ctt_w14Q3ZBK
👉 Copied to: recordings/ready_to_code/20241001_1612_batch_ctt_group_w14Q3ZBK_game_71_words.csv
✅ recordings/20241010_1613_ctt_w161Z2ZS
👉 Copied to: recordings/ready_to_code/20241010_1613_batch_ctt_group_w161Z2ZS_game_72_words.csv
❌ multiple files found for d06e7052-5c9a-4755-a3bd-69d04cd2676e for 20241004_1934_ctt_w1QGZVVV
✅ recordings/20241004_1934_ctt_w1QGZVVV
👉 Copied to: recordings/ready_to_code/20241004_1934_batch_ctt_group_w1QGZVVV_game_73_words.csv
✅ recordings/20241028_1752_ctt_w1TT3ZQF
👉 Copied to: recordings/ready_to_code/20241028_1752_batch_ctt_group_w1TT3ZQF_game_74_words.csv
✅ recordings/20240923_1531_CTT_W1GV2488
👉 Copied to: recordings/ready_to_code/20240923_1531_batch_CTT_group_W1GV2488_game_75_words.csv
❌ no files match be1708a5-b4c9-48fd-be67-e2dd67073ccd in folder 20241004_1934_ctt_w1P5FN67
❌ no files match c21de943-1dab-4a5a-95d4-055d966eeae1 in folder 20241004_1934_ctt_w1P5FN67
❌ no files match 2c61c83c-23f0-422f-a647-770e8e1a4e46 in folder 20241004_1934_ctt_w1P5FN67
❌ no words in recordings/20241004_1934_ctt_w1P5FN67
✅ recordings/20241028_1752_ctt_w15NYG7J
👉 Copied to: recordings/ready_to_code/20241028_1752_batch_ctt_group_w15NYG7J_game_77_words.csv
✅ recordings/20241001_1844_ctt_w1ZN9C4K
👉 Copied to: recordings/ready_to_code/20241001_1844_batch_ctt_group_w1ZN9C4K_game_78_words.csv
✅ recordings/20240920_1732_CT_topMWAGR8
👉 Copied to: recordings/ready_to_code/20240920_1732_batch_CT_group_topMWAGR8_game_79_words.csv
✅ recordings/20240930_1406_ctt_w1EG2HPK
👉 Copied to: recordings/ready_to_code/20240930_1406_batch_ctt_group_w1EG2HPK_game_80_words.csv
✅ recordings/20241009_1402_ctt_w1PSGC4A
👉 Copied to: recordings/ready_to_code/20241009_1402_batch_ctt_group_w1PSGC4A_game_81_words.csv
✅ recordings/20241029_1443_ctt_w13MRB85
👉 Copied to: recordings/ready_to_code/20241029_1443_batch_ctt_group_w13MRB85_game_82_words.csv
✅ recordings/20241023_1611_ctt_w1S6NHW5
👉 Copied to: recordings/ready_to_code/20241023_1611_batch_ctt_group_w1S6NHW5_game_83_words.csv
✅ recordings/20240923_1531_CTT_W1F6JV7K
👉 Copied to: recordings/ready_to_code/20240923_1531_batch_CTT_group_W1F6JV7K_game_84_words.csv
✅ recordings/20241001_1844_ctt_w118039V
👉 Copied to: recordings/ready_to_code/20241001_1844_batch_ctt_group_w118039V_game_85_words.csv
✅ recordings/20241002_1834_ctt_w1D6VE2S
👉 Copied to: recordings/ready_to_code/20241002_1834_batch_ctt_group_w1D6VE2S_game_86_words.csv
✅ recordings/20241023_1611_ctt_w1J3WF4R
👉 Copied to: recordings/ready_to_code/20241023_1611_batch_ctt_group_w1J3WF4R_game_87_words.csv
✅ recordings/20241009_1402_ctt_w1WHVADR
👉 Copied to: recordings/ready_to_code/20241009_1402_batch_ctt_group_w1WHVADR_game_88_words.csv
❌ no files match 928b4609-1a06-4fa2-9493-58f969948316 in folder 20241007_1905_ctt_w1WWWH1A
✅ recordings/20241007_1905_ctt_w1WWWH1A
👉 Copied to: recordings/ready_to_code/20241007_1905_batch_ctt_group_w1WWWH1A_game_89_words.csv
✅ recordings/20241009_1402_ctt_w1JXTYFB
👉 Copied to: recordings/ready_to_code/20241009_1402_batch_ctt_group_w1JXTYFB_game_90_words.csv
❌ no files match c8bc3c79-d4b5-43da-9806-31cb37a6e7de in folder 20240930_1406_ctt_w1KN891H
❌ no files match b4743212-b255-4039-bbad-3f3b559b7ece in folder 20240930_1406_ctt_w1KN891H
❌ no words in recordings/20240930_1406_ctt_w1KN891H
✅ recordings/20241002_1834_ctt_w1Z78HC7
👉 Copied to: recordings/ready_to_code/20241002_1834_batch_ctt_group_w1Z78HC7_game_92_words.csv
✅ recordings/20241002_2139_ctt_w1D5CBGP
👉 Copied to: recordings/ready_to_code/20241002_2139_batch_ctt_group_w1D5CBGP_game_93_words.csv
✅ recordings/20241023_1611_ctt_w11BGNH5
👉 Copied to: recordings/ready_to_code/20241023_1611_batch_ctt_group_w11BGNH5_game_94_words.csv
✅ recordings/20241023_1611_ctt_w1JM1GY8
👉 Copied to: recordings/ready_to_code/20241023_1611_batch_ctt_group_w1JM1GY8_game_95_words.csv
✅ recordings/20241029_1443_ctt_w1QWTZ84
👉 Copied to: recordings/ready_to_code/20241029_1443_batch_ctt_group_w1QWTZ84_game_96_words.csv
❌ no files match 31559684-0341-4698-b72e-85bf89caf965 in folder 20241002_2139_ctt_w15ZSBPE
❌ missing in recordings/20241002_2139_ctt_w15ZSBPE
❌ no words in recordings/20241002_2139_ctt_w15ZSBPE
✅ recordings/20241010_1613_ctt_w132SC1R
👉 Copied to: recordings/ready_to_code/20241010_1613_batch_ctt_group_w132SC1R_game_98_words.csv
✅ recordings/20240926_2049_ctt_w1SZVCS1
👉 Copied to: recordings/ready_to_code/20240926_2049_batch_ctt_group_w1SZVCS1_game_99_words.csv
✅ recordings/20241023_1936_ctt_w1DPZPJQ
👉 Copied to: recordings/ready_to_code/20241023_1936_batch_ctt_group_w1DPZPJQ_game_100_words.csv
✅ recordings/20241029_1443_ctt_w15G16J5
👉 Copied to: recordings/ready_to_code/20241029_1443_batch_ctt_group_w15G16J5_game_101_words.csv
❌ no files match 81c03fdf-af93-49e4-bc5a-6d70b4575245 in folder 20240930_1406_ctt_w1XJW966
✅ recordings/20240930_1406_ctt_w1XJW966
👉 Copied to: recordings/ready_to_code/20240930_1406_batch_ctt_group_w1XJW966_game_102_words.csv
✅ recordings/20241002_2139_ctt_w1KTYKB2
👉 Copied to: recordings/ready_to_code/20241002_2139_batch_ctt_group_w1KTYKB2_game_103_words.csv
❌ multiple files found for 09bceac9-28f9-4698-b171-24ec08cfabe1 for 20241001_1844_ctt_w1D14B4N
✅ recordings/20241001_1844_ctt_w1D14B4N
👉 Copied to: recordings/ready_to_code/20241001_1844_batch_ctt_group_w1D14B4N_game_104_words.csv
✅ recordings/20241002_2139_ctt_w16S8WSX
👉 Copied to: recordings/ready_to_code/20241002_2139_batch_ctt_group_w16S8WSX_game_105_words.csv
✅ recordings/20241023_1611_ctt_w1ZGPERF
👉 Copied to: recordings/ready_to_code/20241023_1611_batch_ctt_group_w1ZGPERF_game_106_words.csv
✅ recordings/20241029_1443_ctt_w1C6VDQD
👉 Copied to: recordings/ready_to_code/20241029_1443_batch_ctt_group_w1C6VDQD_game_107_words.csv
✅ recordings/20241002_1834_ctt_w1NBBKXN
👉 Copied to: recordings/ready_to_code/20241002_1834_batch_ctt_group_w1NBBKXN_game_108_words.csv
✅ recordings/20241024_1555_ctt_w1JW5CYX
👉 Copied to: recordings/ready_to_code/20241024_1555_batch_ctt_group_w1JW5CYX_game_109_words.csv
✅ recordings/20241024_1823_ctt_w13EJKNT
👉 Copied to: recordings/ready_to_code/20241024_1823_batch_ctt_group_w13EJKNT_game_110_words.csv
✅ recordings/20240923_1531_CTT_W1KQKTMQ
👉 Copied to: recordings/ready_to_code/20240923_1531_batch_CTT_group_W1KQKTMQ_game_111_words.csv
✅ recordings/20241002_1834_ctt_w1R4YE3K
👉 Copied to: recordings/ready_to_code/20241002_1834_batch_ctt_group_w1R4YE3K_game_112_words.csv
✅ recordings/20241023_1611_ctt_w13YY4JE
👉 Copied to: recordings/ready_to_code/20241023_1611_batch_ctt_group_w13YY4JE_game_113_words.csv
✅ recordings/20241009_1402_ctt_w1Z3WSK0
👉 Copied to: recordings/ready_to_code/20241009_1402_batch_ctt_group_w1Z3WSK0_game_114_words.csv
❌ no files match b361bb6a-bf63-482e-9db6-b5b619e2336a in folder 20241023_1611_ctt_w1ZK82MK
❌ no files match 074d3a33-2e79-44b3-9047-30612b6199f5 in folder 20241023_1611_ctt_w1ZK82MK
❌ no files match 7893716d-edbd-4953-bd74-5b8afc1ef945 in folder 20241023_1611_ctt_w1ZK82MK
❌ no files match 30c99391-86ab-461c-bdb6-53687b1b1131 in folder 20241023_1611_ctt_w1ZK82MK
❌ no files match 39df55a9-3388-4f46-906e-54a4d139fdd4 in folder 20241023_1611_ctt_w1ZK82MK
✅ recordings/20241023_1611_ctt_w1ZK82MK
👉 Copied to: recordings/ready_to_code/20241023_1611_batch_ctt_group_w1ZK82MK_game_115_words.csv
✅ recordings/20241002_1834_ctt_w1XXG21B
👉 Copied to: recordings/ready_to_code/20241002_1834_batch_ctt_group_w1XXG21B_game_116_words.csv
✅ recordings/20241023_1611_ctt_w1QKRWR5
👉 Copied to: recordings/ready_to_code/20241023_1611_batch_ctt_group_w1QKRWR5_game_117_words.csv
✅ recordings/20241002_2139_ctt_w1VX5SDK
👉 Copied to: recordings/ready_to_code/20241002_2139_batch_ctt_group_w1VX5SDK_game_118_words.csv
✅ recordings/20241009_1402_ctt_w1C3XZZP
👉 Copied to: recordings/ready_to_code/20241009_1402_batch_ctt_group_w1C3XZZP_game_119_words.csv
✅ recordings/20241002_2139_ctt_w1DD4FSV
👉 Copied to: recordings/ready_to_code/20241002_2139_batch_ctt_group_w1DD4FSV_game_120_words.csv
✅ recordings/20241001_1844_ctt_w1D0JTPP
👉 Copied to: recordings/ready_to_code/20241001_1844_batch_ctt_group_w1D0JTPP_game_121_words.csv
✅ recordings/20240930_1406_ctt_w1DX9HBX
👉 Copied to: recordings/ready_to_code/20240930_1406_batch_ctt_group_w1DX9HBX_game_122_words.csv
✅ recordings/20241009_1402_ctt_w1V33MYT
👉 Copied to: recordings/ready_to_code/20241009_1402_batch_ctt_group_w1V33MYT_game_123_words.csv
✅ recordings/20240923_1531_CTT_W1FVP9QY
👉 Copied to: recordings/ready_to_code/20240923_1531_batch_CTT_group_W1FVP9QY_game_124_words.csv
✅ recordings/20241024_1555_ctt_w1D55SEM
👉 Copied to: recordings/ready_to_code/20241024_1555_batch_ctt_group_w1D55SEM_game_125_words.csv
✅ recordings/20240920_1732_CT_topFDAGM1
👉 Copied to: recordings/ready_to_code/20240920_1732_batch_CT_group_topFDAGM1_game_126_words.csv
✅ recordings/20240926_1419_ctt_w1VYDY3G
👉 Copied to: recordings/ready_to_code/20240926_1419_batch_ctt_group_w1VYDY3G_game_127_words.csv
✅ recordings/20241001_1612_ctt_w1Z7GFPS

In [34]:
conversation_words

Empty DataFrame
Columns: [conversation_id, position]
Index: []

# Try to understand missing recordings

In [12]:
recording_stats = []
for game_index, group in data.groupby("game"):
    for i, participant in group.iterrows():
        folder = f"{recordings_folder}/{participant['recordingsFolder']}"
        stats = {
            "game": game_index,
            "participant": i,
            "folder": folder,
            "folder_exists": os.path.exists(folder),
        }

        recording_stats.append(stats)

recording_stats_df = pd.DataFrame(recording_stats)
recording_stats_df

      game  participant                                 folder  folder_exists
0        0            0  recordings/20241001_1844_ctt_w1V35R4E           True
1        0            1  recordings/20241001_1844_ctt_w1V35R4E           True
2        1            2  recordings/20241004_1934_ctt_w1M7AWTB           True
3        1            3  recordings/20241004_1934_ctt_w1M7AWTB           True
4        2            4  recordings/20240923_1531_CTT_W1GY0Y4B           True
...    ...          ...                                    ...            ...
1026   513         1026  recordings/20241217_1837_w2s19_BS9KEY           True
1027   514         1027  recordings/20241219_1734_w2s26_19WP2C           True
1028   514         1028  recordings/20241219_1734_w2s26_19WP2C           True
1029   515         1029  recordings/20241217_1837_w2s19_RFCWYF           True
1030   515         1030  recordings/20241217_1837_w2s19_RFCWYF           True

[1031 rows x 4 columns]

In [13]:
data.head()

,treatment,game,position,batchId,batchName,deliberationId,sampleId,gameId,recordingIds,recordingsFolder,...,partner_race_Native Hawaiian or other Pacific Islander,party_difference,years_seniority,guessPartnerPartyError,guessPartnerPartyExtremity,guessPartnerTopicError,guessPartnerTopicExtremity,overall_demographic_difference,duration_Part1,duration_Part2
0,wave_1_fundNeedleExchange_dem_0_rep_0,0,0,01J94PCAWCN6AS2Q7K9GHF45KV,ctt_w1_s6_CR,4c923fdd-fd15-4780-9f16-5a60e040def6,667c2bfe-8401-4272-9ea6-44f0aef7c38c,01J94SKS2GJ71CT03G7XV35R4E,['252fcba0-f6df-41af-ae27-3516965e50b4'],20241001_1844_ctt_w1V35R4E,...,0.0,1.000,-4.0,0.00000,0.50000,0.000000,0.500000,5.991534,1466,1680.0
1,wave_1_fundNeedleExchange_dem_0_rep_0,0,1,01J94PCAWCN6AS2Q7K9GHF45KV,ctt_w1_s6_CR,a125d806-2bcf-496a-a9ae-f727a2803d2f,0be567b7-cda5-42eb-9098-c0187b0225c3,01J94SKS2GJ71CT03G7XV35R4E,['c3eac583-9b28-4756-8cc6-947d2fc09e31'],20241001_1844_ctt_w1V35R4E,...,0.0,1.000,4.0,0.16666,0.33334,0.500000,0.000000,5.991534,382,929.0
2,wave_1_fundNeedleExchange_dem_0_rep_5,1,0,01J9CGDS649P6NV967E7YCNXS8,ctt_w1_s11_CR,4d8ce909-c9ec-411d-9fa5-9ea02bf0e0b5,3fe79b64-0703-4a0e-8389-878ba6f5a386,01J9CJRDKZCGRP8NWM0RM7AWTB,['1cfdf05f-0eb7-4311-bce8-fbaca8f229a5'],20241004_1934_ctt_w1M7AWTB,...,0.0,0.833,-21.0,0.16634,0.16666,0.333333,0.000000,6.467071,256,882.0
3,wave_1_fundNeedleExchange_dem_0_rep_5,1,1,01J9CGDS649P6NV967E7YCNXS8,ctt_w1_s11_CR,d3b80e89-be64-49a0-a26b-1c43b8aec6df,b9c46cfa-6b1d-4f62-8efa-2362ac93dfe1,01J9CJRDKZCGRP8NWM0RM7AWTB,['eb2785d2-ee20-488a-9bd8-d8da06724910'],20241004_1934_ctt_w1M7AWTB,...,0.0,0.833,21.0,0.00000,0.50000,0.000000,0.500000,6.467071,319,954.0
4,wave_1_fundNeedleExchange_dem_0_rep_6,2,0,01J8FR4S38XRPMEGQSJ4WGVSTX,CTT_W1_S3,3d46635f-680a-470e-a835-29f826a9471e,2bd517af-2e4c-41f8-9dea-ee2eff4b2ca4,01J8FVGE4701CXJQ35AHGY0Y4B,"['299867da-d96e-4ad4-9f41-e3033ac95261', '79d5...",20240923_1531_CTT_W1GY0Y4B,...,0.0,0.833,-18.0,0.00033,0.33333,0.333333,0.166667,5.007841,638,1763.0

In [14]:
recording_stats_df["folder_exists"].value_counts()

folder_exists
True     1025
False       6
Name: count, dtype: int64

In [15]:
data['recordings_downloaded'] = data['recordingsFolder'].apply(lambda x: os.path.exists(f"{recordings_folder}/{x}"))
data['recordings_downloaded'].value_counts()

recordings_downloaded
True     1025
False       6
Name: count, dtype: int64

In [16]:
data[(data['discussion_happened'] == True) & (data['recordings_downloaded'] == False)]

,treatment,game,position,batchId,batchName,deliberationId,sampleId,gameId,recordingIds,recordingsFolder,...,party_difference,years_seniority,guessPartnerPartyError,guessPartnerPartyExtremity,guessPartnerTopicError,guessPartnerTopicExtremity,overall_demographic_difference,duration_Part1,duration_Part2,recordings_downloaded
569,wave_2_capAndTrade_dem_6_rep_0,285,0,01JEY2M6EVFAZ4WGZWP29BHSV8,w2s12_ctt_prolific,2370bb1e-7e95-499c-8fa4-c0bb4bd86030,a24cd8c8-14ca-440c-a7c2-0f02a2210267,01JEY3WNNTDPYH8RA1V3J5C3YN,['9d59e259-b76f-49f1-8adc-98d53cc1f1c7'],20241212_1838_w2s12_J5C3YN,...,1.0,8.0,NaN,NaN,NaN,NaN,4.892180,346,NaN,False
570,wave_2_capAndTrade_dem_6_rep_0,285,1,01JEY2M6EVFAZ4WGZWP29BHSV8,w2s12_ctt_prolific,14d93321-79cd-4798-a5cd-92f4d296115d,bf7c4436-2fc8-408a-b387-11d63ef69455,01JEY3WNNTDPYH8RA1V3J5C3YN,['be04edee-ff60-43fd-a8bd-44851d0e0af6'],20241212_1838_w2s12_J5C3YN,...,1.0,-8.0,0.00000,0.50000,0.333333,0.166667,4.892180,320,856.0,False
671,wave_2_cubaEmbargo_dem_3_rep_5,336,0,01JEY9A5H2086RQ622BE75Z2G2,w2s14_ctt_prolific,6627c9cc-2e2e-4080-af5e-287acefea3e6,f4198256-96f3-4699-ae71-2f58a815e872,01JEYARC27QPQ6WQEFWYDB7Q51,['0b44e767-f403-497a-ab70-2bac49e3af78'],20241212_2035_w2s14_DB7Q51,...,0.5,-12.0,0.16634,0.16666,0.166667,0.166667,5.184515,321,845.0,False
672,wave_2_cubaEmbargo_dem_3_rep_5,336,1,01JEY9A5H2086RQ622BE75Z2G2,w2s14_ctt_prolific,8dbdfad9-1ef8-4456-b553-d5a9a9f58167,ced582ea-2938-4640-83b5-dcbc791e76b1,01JEYARC27QPQ6WQEFWYDB7Q51,['3f2202a7-4b7f-49db-9b51-87b82297aef9'],20241212_2035_w2s14_DB7Q51,...,0.5,12.0,0.00033,0.16667,0.333333,0.333333,5.184515,392,925.0,False

In [17]:
data.columns

Index(['treatment', 'game', 'position', 'batchId', 'batchName',
       'deliberationId', 'sampleId', 'gameId', 'recordingIds',
       'recordingsFolder',
       ...
       'party_difference', 'years_seniority', 'guessPartnerPartyError',
       'guessPartnerPartyExtremity', 'guessPartnerTopicError',
       'guessPartnerTopicExtremity', 'overall_demographic_difference',
       'duration_Part1', 'duration_Part2', 'recordings_downloaded'],
      dtype='object', length=279)